
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace DollysLilChurch
{
	public class DollysLilChurchAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11712, 0, 0, 34}, {11713, -1, 1, 34}, {12059, 0, 1, 34}// 18	19	20	
			, {11728, -1, 3, 20}, {11728, 0, 3, 20}, {11728, 1, 3, 20}// 21	57	58	
			, {4032, 0, 0, 14}, {11131, 3, 2, 0}, {11132, -2, 3, 0}// 59	71	76	
			, {11717, 3, 3, 0}, {11131, -3, 3, 0}, {11131, -3, 2, 0}// 77	78	79	
			, {20345, 3, 3, 0}, {20345, 3, 2, 0}, {20345, 3, 1, 0}// 80	81	82	
			, {20345, 3, 0, 0}, {20345, 2, 3, 0}, {20345, 2, 2, 0}// 83	84	85	
			, {20345, 2, 1, 0}, {20345, 2, 0, 0}, {20345, 1, 3, 0}// 86	87	88	
			, {20345, 1, 2, 0}, {20345, 1, 1, 0}, {20345, 1, 0, 0}// 89	90	91	
			, {20345, 0, 3, 0}, {20345, 0, 2, 0}, {20345, 0, 1, 0}// 92	93	94	
			, {20345, 0, 0, 0}, {20345, -1, 3, 0}, {20345, -1, 2, 0}// 95	96	97	
			, {20345, -1, 1, 0}, {20345, -1, 0, 0}, {20345, -2, 3, 0}// 98	99	100	
			, {20345, -2, 2, 0}, {20345, -2, 1, 0}, {20345, -2, 0, 0}// 101	102	103	
			, {11131, 3, -1, 0}, {11131, 3, -2, 0}, {11132, 3, -3, 0}// 127	128	129	
			, {11132, 2, -3, 0}, {11132, -1, -3, 0}, {11132, -2, -3, 0}// 130	131	132	
			, {11720, -3, -3, 0}, {11131, -3, -1, 0}, {11131, -3, -2, 0}// 133	134	135	
			, {20345, 3, -1, 0}, {20345, 3, -2, 0}, {20345, 2, -1, 0}// 136	137	138	
			, {20345, 2, -2, 0}, {20345, 1, -1, 0}, {20345, 1, -2, 0}// 139	140	141	
			, {20345, 0, -1, 0}, {20345, 0, -2, 0}, {20345, -1, -1, 0}// 142	143	144	
			, {20345, -1, -2, 0}, {20345, -2, -1, 0}, {20345, -2, -2, 0}// 145	146	147	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DollysLilChurchAddonDeed();
			}
		}

		[ Constructable ]
		public DollysLilChurchAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2539, 2, 3, 31, 33, -1, "Heart", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2539, -1, 3, 36, 33, -1, "Heart", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2539, 3, 2, 44, 33, -1, "Heart", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2539, 3, 1, 34, 33, -1, "Heart", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2539, 4, 3, 36, 33, -1, "Heart", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2539, 0, 3, 35, 33, -1, "Heart", 1);// 6
			AddComplexComponent( (BaseAddon) this, 39783, -1, 0, 54, 2845, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 39783, -1, 1, 54, 2845, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 39783, -1, 2, 53, 2845, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 39792, 0, 0, 57, 2845, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 39792, 0, 1, 57, 2845, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 39792, 0, 2, 57, 2845, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 39782, 1, 0, 54, 2845, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 39782, 1, 1, 54, 2845, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 39782, 1, 2, 54, 2845, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 19602, 0, 0, 28, 0, -1, "Church Bell", 1);// 16
			AddComplexComponent( (BaseAddon) this, 19605, -1, 1, 27, 0, -1, "Church Bell", 1);// 17
			AddComplexComponent( (BaseAddon) this, 39783, -2, 3, 22, 2845, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 39783, -2, 4, 22, 2845, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 39783, -2, 2, 22, 2845, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 39783, -2, 1, 22, 2845, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 39783, -2, 0, 22, 2845, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 39783, -1, 4, 25, 2845, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 39783, -1, 3, 25, 2845, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 39783, -1, 2, 25, 2845, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 39783, -1, 1, 25, 2845, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 39783, -1, 0, 25, 2845, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 39783, 0, 0, 28, 2845, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 39783, 0, 1, 28, 2845, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 39783, 0, 2, 28, 2845, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 39783, 0, 3, 28, 2845, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 39783, 0, 4, 28, 2845, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 39781, 1, 0, 31, 2845, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 39781, 1, 1, 31, 2845, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 39781, 1, 2, 31, 2845, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 39781, 1, 3, 31, 2845, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 39781, 1, 4, 31, 2845, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 39782, 2, 0, 28, 2845, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 39782, 2, 1, 28, 2845, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 39782, 2, 2, 28, 2845, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 39782, 2, 3, 28, 2845, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 39782, 2, 4, 28, 2845, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 39782, 3, 0, 25, 2845, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 39782, 3, 1, 25, 2845, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 39782, 3, 2, 25, 2845, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 39782, 3, 3, 25, 2845, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 39782, 3, 4, 25, 2845, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 39782, 4, 1, 22, 2845, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 39782, 4, 0, 22, 2845, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 39782, 4, 2, 22, 2845, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 39782, 4, 3, 22, 2845, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 39782, 4, 4, 22, 2845, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 40611, -1, 1, 6, 26, -1, "Flowers", 1);// 60
			AddComplexComponent( (BaseAddon) this, 17087, -1, 0, 5, 0, -1, "Marriage book", 1);// 61
			AddComplexComponent( (BaseAddon) this, 40608, 1, 0, 0, 1165, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 40658, -1, 0, 0, 1165, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 40657, -1, 1, 0, 1165, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 40610, -2, 0, 0, 11, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 15783, -2, 2, 1, 406, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 40612, 2, 4, 0, 26, -1, "Flowers", 1);// 67
			AddComplexComponent( (BaseAddon) this, 40612, -1, 4, 0, 26, -1, "Flowers", 1);// 68
			AddComplexComponent( (BaseAddon) this, 39710, -3, 1, 0, 0, 0, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 39710, -3, 0, 0, 0, 0, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 11134, 3, 0, 0, 0, 0, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 11134, 3, 1, 0, 0, 0, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 11133, 2, 3, 0, 0, 0, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 11133, -1, 3, 0, 0, 0, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 2539, 2, -1, 36, 33, -1, "Heart", 1);// 104
			AddComplexComponent( (BaseAddon) this, 39783, -2, -2, 22, 2845, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 39783, -2, -1, 22, 2845, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 39783, -1, -1, 25, 2845, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 39783, -1, -2, 25, 2845, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 39783, 0, -2, 28, 2845, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 39783, 0, -1, 28, 2845, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 39781, 1, -2, 31, 2845, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 39781, 1, -1, 31, 2845, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 39782, 2, -2, 28, 2845, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 39782, 2, -1, 28, 2845, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 39782, 3, -2, 25, 2845, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 39782, 3, -1, 25, 2845, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 39782, 4, -1, 22, 2845, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 39782, 4, -2, 22, 2845, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 40608, 1, -1, 0, 1165, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 40659, -1, -1, 0, 1165, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 40689, -2, -2, 0, 0, 0, "Candles", 1);// 121
			AddComplexComponent( (BaseAddon) this, 15780, 2, -2, 1, 406, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 15780, -1, -2, 1, 406, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 15783, -2, -1, 1, 406, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 39709, 1, -3, 0, 0, 0, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 39709, 0, -3, 0, 0, 0, "", 1);// 126

		}

		public DollysLilChurchAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DollysLilChurchAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DollysLilChurchAddon();
			}
		}

		[Constructable]
		public DollysLilChurchAddonDeed()
		{
			Name = "DollysLilChurch";
		}

		public DollysLilChurchAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}