
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace KitsCaveHouseThree
{
	public class KitsCaveHouseThreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3245, -2, 5, 6}, {6013, 7, 7, 5}, {6013, 7, 6, 5}// 1	28	29	
			, {6013, 7, 5, 5}, {6013, 6, 7, 5}, {6013, 6, 6, 5}// 30	31	32	
			, {6013, 6, 5, 5}, {6013, 5, 7, 5}, {6013, 5, 6, 5}// 33	34	35	
			, {6013, 5, 5, 5}, {6013, 4, 7, 5}, {6013, 4, 6, 5}// 36	37	38	
			, {6013, 4, 5, 5}, {6013, 3, 7, 5}, {6013, 3, 6, 5}// 39	40	41	
			, {6013, 3, 5, 5}, {6013, 2, 7, 5}, {6013, 2, 6, 5}// 42	43	44	
			, {6013, 2, 5, 5}, {6013, 1, 7, 5}, {6013, 1, 6, 5}// 45	46	47	
			, {6013, 1, 5, 5}, {6013, 0, 7, 5}, {6013, 0, 6, 5}// 48	49	50	
			, {6013, 0, 5, 5}, {6013, -1, 7, 5}, {6013, -1, 6, 5}// 51	52	53	
			, {6013, -1, 5, 5}, {6013, -2, 7, 5}, {6013, -2, 6, 5}// 54	55	56	
			, {6013, -2, 5, 5}, {6055, 4, 4, 5}, {6050, 3, 4, 5}// 57	88	89	
			, {6046, 4, 3, 5}, {3339, 2, 1, 5}, {3339, 1, 2, 5}// 90	91	92	
			, {3339, 2, -1, 5}, {3203, -2, 2, 5}, {3203, -1, 1, 5}// 93	94	95	
			, {3203, 1, -1, 5}, {3203, 2, -2, 5}, {3210, 2, 4, 5}// 96	97	98	
			, {3210, 4, 2, 5}, {6046, 4, 0, 5}, {6046, 4, 1, 5}// 99	100	101	
			, {6046, 4, 2, 5}, {6046, 4, 3, 5}, {6055, 4, 4, 5}// 102	103	104	
			, {6049, 0, 4, 5}, {6049, 3, 4, 5}, {6049, 2, 4, 5}// 105	106	107	
			, {6049, 1, 4, 5}, {13422, 3, 3, 5}, {3204, 1, -3, 26}// 108	109	110	
			, {3204, 3, -6, 26}, {11516, -2, -2, 27}, {11514, -1, -1, 41}// 111	113	114	
			, {3204, -2, -7, 47}, {3204, -2, -4, 48}, {3204, 2, -3, 29}// 115	116	117	
			, {3245, 7, -3, 6}, {3245, 6, -3, 6}, {3245, 5, -3, 6}// 154	155	156	
			, {3245, 7, -5, 6}, {3245, 6, -5, 6}, {3245, 5, -5, 6}// 157	158	159	
			, {3245, 7, -7, 6}, {3245, 6, -7, 6}, {3245, 5, -7, 6}// 160	161	162	
			, {3244, 5, -1, 6}, {3244, 5, -2, 6}, {3244, 5, -3, 6}// 163	164	165	
			, {3244, 5, -6, 6}, {3244, 5, -7, 6}, {3255, 0, 4, 5}// 166	167	168	
			, {3204, 2, 4, 5}, {6055, 3, 4, 5}, {6050, 2, 4, 5}// 169	170	171	
			, {6050, 0, 4, 5}, {6049, 1, 4, 5}, {6014, 4, 4, 5}// 172	173	174	
			, {6014, 3, 4, 5}, {6014, 2, 4, 5}, {6014, 1, 4, 5}// 175	176	177	
			, {6014, 0, 4, 5}, {3237, -1, 4, 5}, {6049, -1, 4, 5}// 178	179	180	
			, {6014, -1, 4, 5}, {3220, -1, -2, 27}, {3220, -2, -1, 28}// 181	183	184	
			, {13422, 0, -2, 25}, {13422, -2, 0, 25}, {13422, 0, -1, 26}// 185	186	187	
			, {13422, -2, -2, 25}, {13422, -1, -2, 25}, {13422, -2, -1, 25}// 188	189	190	
			, {13422, 0, -1, 25}, {13422, -1, -1, 25}, {13422, -1, 0, 25}// 191	192	193	
			, {3245, 7, -7, 5}, {3245, 6, -7, 5}, {3245, 5, -7, 5}// 197	198	199	
			, {3245, 7, -5, 5}, {3245, 6, -5, 5}, {3245, 5, -5, 6}// 200	201	202	
			, {3244, 5, -2, 5}, {3244, 5, -3, 5}, {3244, 5, -6, 5}// 203	204	205	
			, {3244, 5, -7, 5}, {3245, 7, -3, 5}, {3245, 6, -3, 5}// 206	207	208	
			, {3245, 5, -3, 5}, {6013, 7, 4, 5}, {6013, 7, 3, 5}// 209	248	249	
			, {6013, 7, 2, 5}, {6013, 7, 1, 5}, {6013, 7, 0, 5}// 250	251	252	
			, {6013, 7, -1, 5}, {6013, 7, -2, 5}, {6013, 7, -3, 5}// 253	254	255	
			, {6013, 7, -6, 5}, {6013, 7, -7, 5}, {6013, 6, 4, 5}// 256	257	258	
			, {6013, 6, 3, 5}, {6013, 6, 2, 5}, {6013, 6, 1, 5}// 259	260	261	
			, {6013, 6, 0, 5}, {6013, 6, -1, 5}, {6013, 6, -2, 5}// 262	263	264	
			, {6013, 6, -3, 5}, {6013, 6, -6, 5}, {6013, 6, -7, 5}// 265	266	267	
			, {6013, 5, 4, 5}, {6013, 5, 3, 5}, {6013, 5, 2, 5}// 268	269	270	
			, {6013, 5, 1, 5}, {6013, 5, 0, 5}, {6013, 5, -1, 5}// 271	272	273	
			, {6013, 5, -2, 5}, {6013, 5, -3, 5}, {6013, 5, -6, 5}// 274	275	276	
			, {6013, 5, -7, 5}, {3335, 3, 3, 5}, {3516, 3, 3, 5}// 277	278	279	
			, {6055, 4, 3, 5}, {6058, 3, 3, 5}, {3333, 1, 3, 5}// 280	281	282	
			, {13603, 0, 3, 5}, {13451, 0, 3, 6}, {6014, 3, 3, 5}// 283	284	285	
			, {6039, 2, 3, 5}, {6039, 1, 3, 5}, {6014, 4, 3, 5}// 286	287	288	
			, {3231, -1, 3, 5}, {6039, -1, 3, 5}, {3517, 3, 2, 5}// 289	290	293	
			, {3204, 4, 2, 5}, {13488, 1, 2, 41}, {6045, 4, 2, 5}// 294	295	296	
			, {3339, 1, 2, 5}, {13456, 2, 2, 5}, {13597, 0, 2, 5}// 297	298	299	
			, {13591, 1, 2, 16}, {13585, 1, 2, 27}, {6039, 0, 2, 5}// 300	301	302	
			, {6039, 1, 2, 5}, {6039, 3, 2, 5}, {6014, 4, 2, 5}// 303	304	305	
			, {3339, -1, 2, 5}, {3203, -2, 2, 5}, {6039, -1, 2, 4}// 306	307	308	
			, {6014, -2, 2, 5}, {3255, 0, -2, 25}, {11514, 5, -6, 11}// 309	311	312	
			, {3335, 0, 0, 26}, {3237, 4, -1, 5}, {3255, 4, 0, 5}// 313	314	315	
			, {3234, 0, -2, 25}, {3231, 3, -1, 5}, {3204, 3, -6, 25}// 316	317	318	
			, {3518, 0, 0, 25}, {6047, 0, -2, 25}, {6040, 0, -1, 25}// 319	320	321	
			, {6040, 0, 0, 25}, {13446, 2, 1, 40}, {6046, 4, 0, 5}// 322	325	326	
			, {6045, 4, 1, 5}, {6045, 4, 0, 5}, {3333, 3, 1, 5}// 327	328	329	
			, {3339, 2, 1, 5}, {3339, 2, -1, 5}, {3203, 2, -2, 5}// 330	331	332	
			, {3203, 1, -1, 5}, {13573, 3, 0, 5}, {13485, 3, 0, 6}// 333	334	335	
			, {13567, 2, 0, 5}, {13561, 2, 1, 17}, {13555, 2, 1, 27}// 336	337	338	
			, {6039, 3, 1, 5}, {6039, 2, 1, 5}, {6039, 2, 0, 5}// 339	340	341	
			, {6039, 3, -1, 5}, {6039, 2, -1, 5}, {6014, 1, -1, 5}// 342	343	344	
			, {6014, 2, -2, 5}, {6014, 4, 1, 5}, {6014, 4, 0, 5}// 345	346	347	
			, {6014, 4, -1, 5}, {3516, -1, -1, 25}, {3212, -1, -2, 25}// 348	417	418	
			, {3211, -2, -1, 25}, {3256, -2, 0, 25}, {3235, -2, 1, 26}// 419	420	421	
			, {3204, -2, -2, 25}, {6054, -2, -2, 25}, {6052, -2, 0, 25}// 422	423	424	
			, {6051, -2, -1, 25}, {6048, -1, -2, 25}, {6040, -1, 0, 25}// 425	426	427	
			, {6040, -1, -1, 25}, {3203, -1, 1, 5}, {6014, -1, 1, 5}// 428	432	433	
			, {3219, -2, -7, 25}, {11516, -6, 5, 11}, {3244, -7, 7, 6}// 463	590	591	
			, {3244, -7, 6, 6}, {3244, -7, 5, 6}, {3245, -6, 5, 7}// 592	593	594	
			, {3245, -7, 5, 6}, {3245, -3, 5, 6}, {3244, -5, 7, 6}// 595	596	597	
			, {3244, -5, 6, 6}, {3244, -5, 5, 6}, {3244, -3, 7, 6}// 598	599	600	
			, {3244, -3, 6, 6}, {3244, -3, 5, 5}, {6013, -3, 7, 5}// 601	602	626	
			, {6013, -3, 6, 5}, {6013, -3, 5, 5}, {6013, -6, 7, 5}// 627	628	629	
			, {6013, -6, 6, 5}, {6013, -6, 5, 5}, {6013, -7, 7, 5}// 630	631	632	
			, {6013, -7, 6, 5}, {6013, -7, 5, 5}, {3204, -3, 1, 26}// 633	634	650	
			, {3204, -6, 3, 26}, {3204, -4, -2, 48}, {3204, -4, -7, 48}// 651	652	653	
			, {3204, -4, 2, 26}, {3204, -7, -3, 48}, {3204, -6, 3, 25}// 654	655	786	
			, {3219, -7, -2, 25}// 847	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KitsCaveHouseThreeAddonDeed();
			}
		}

		[ Constructable ]
		public KitsCaveHouseThreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2273, -2, 8, 0, 696, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2273, -1, 8, 0, 696, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2273, 0, 8, 0, 696, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2273, 1, 8, 0, 696, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2273, 3, 8, 0, 696, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2273, 2, 8, 0, 696, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2273, 4, 8, 0, 696, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2273, 5, 8, 0, 696, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2273, 6, 8, 0, 696, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2273, 7, 8, 0, 696, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2273, 8, 8, 0, 696, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2273, 8, 7, 0, 696, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2273, 8, 6, 0, 696, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2273, 8, 5, 0, 696, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 628, 7, 6, 5, 696, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 628, 7, 5, 5, 696, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 624, 6, 7, 5, 696, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 624, 5, 7, 5, 696, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 624, 4, 7, 5, 696, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 624, 3, 7, 5, 696, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 624, 2, 7, 5, 696, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 624, 1, 7, 5, 696, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 624, 0, 7, 5, 696, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 624, -1, 7, 5, 696, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 624, -2, 7, 5, 696, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 625, 7, 7, 5, 696, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1848, 6, 7, 0, 2404, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1848, 6, 6, 0, 2404, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1848, 6, 5, 0, 2404, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1848, 5, 7, 0, 2404, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1848, 5, 6, 0, 2404, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1848, 5, 5, 0, 2404, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1848, 4, 7, 0, 2404, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1848, 4, 6, 0, 2404, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1848, 4, 5, 0, 2404, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1848, 3, 7, 0, 2404, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1848, 3, 6, 0, 2404, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1848, 3, 5, 0, 2404, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1848, 2, 7, 0, 2404, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1848, 2, 6, 0, 2404, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1848, 2, 5, 0, 2404, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1848, 1, 7, 0, 2404, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1848, 1, 6, 0, 2404, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1848, 1, 5, 0, 2404, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1848, 0, 7, 0, 2404, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1848, 0, 6, 0, 2404, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1848, 0, 5, 0, 2404, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1848, -1, 7, 0, 2404, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1848, -1, 6, 0, 2404, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1848, -1, 5, 0, 2404, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1848, -2, 7, 0, 2404, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1848, -2, 6, 0, 2404, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1848, -2, 5, 0, 2404, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1848, 7, 7, 0, 2404, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1848, 7, 6, 0, 2404, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1848, 7, 5, 0, 2404, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 3231, -2, -6, 48, 1368, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 3231, 1, -7, 26, 1368, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 2279, -2, -7, 47, 696, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 2279, -2, -3, 47, 696, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 2281, -2, 3, 35, 696, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 2281, 2, -3, 25, 696, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 2281, 3, -4, 28, 696, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 2276, 2, -7, 25, 696, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 2276, 0, -7, 25, 696, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 46, -2, -4, 45, 696, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 46, -2, -6, 45, 696, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 628, -2, -4, 49, 696, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 628, -2, -5, 49, 696, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 628, -2, -6, 49, 696, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 628, -2, -7, 49, 696, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 624, -2, -8, 49, 696, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 625, -2, -3, 50, 696, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 47, -2, -8, 47, 696, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 45, -2, -3, 47, 696, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 46, -2, -4, 47, 696, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 46, -2, -5, 47, 696, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 46, -2, -6, 47, 696, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 46, -2, -7, 47, 696, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1339, -2, -3, 47, 696, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1339, -2, -4, 47, 696, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1339, -2, -5, 47, 696, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1339, -2, -6, 47, 696, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1339, -2, -7, 47, 696, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 611, -2, -2, 25, 696, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 42, -2, -4, 25, 696, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 43, -2, -6, 25, 696, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 604, -1, -3, 25, 696, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 604, -1, -7, 25, 696, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 605, -2, -7, 25, 696, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 47, 2, -3, 25, 696, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 46, 3, -4, 25, 696, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 46, 3, -5, 25, 696, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 612, -2, 4, 5, 696, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 3231, -2, 0, 26, 1368, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 3231, 0, -2, 26, 1368, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 3231, -2, -2, 26, 1368, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1339, 7, -4, 5, 786, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1339, 7, -5, 5, 786, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1339, 6, -4, 5, 786, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1339, 6, -5, 5, 786, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1339, 5, -4, 5, 786, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1339, 5, -5, 5, 786, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1850, 8, -4, 0, 696, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1850, 8, -5, 0, 696, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 2273, 8, 4, 0, 696, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 2273, 8, 3, 0, 696, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 2273, 8, 2, 0, 696, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 2273, 8, 1, 0, 696, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 2273, 8, 0, 0, 696, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 2273, 8, -1, 0, 696, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 2273, 8, -2, 0, 696, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 2273, 8, -3, 0, 696, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 2273, 8, -8, 0, 696, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 2273, 7, -8, 0, 696, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 2273, 6, -8, 0, 696, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 2273, 5, -8, 0, 696, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 2273, 4, -8, 0, 696, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 2273, 8, -6, 0, 696, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 2273, 8, -7, 0, 696, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 624, 7, -8, 5, 696, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 624, 6, -8, 5, 696, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 624, 5, -8, 5, 696, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 628, 7, 4, 5, 696, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 628, 7, 3, 5, 696, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 628, 7, 2, 5, 696, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 628, 7, 1, 5, 696, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 628, 7, 0, 5, 696, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 628, 7, -1, 5, 696, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 628, 7, -2, 5, 696, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 628, 7, -3, 5, 696, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 628, 7, -4, 5, 696, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 628, 7, -5, 5, 696, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 628, 7, -6, 5, 696, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 628, 7, -7, 5, 696, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 604, -2, 3, 5, 696, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1339, -2, 3, 5, 786, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1339, 4, -5, 5, 786, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1339, 0, 0, 25, 696, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1339, 0, -1, 25, 696, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 2272, 1, -2, 27, 696, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 2272, 3, -3, 25, 696, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 1339, 3, -3, 25, 696, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 1339, 3, -4, 25, 696, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1339, 3, -5, 25, 696, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 1339, 3, -6, 25, 696, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 1339, 2, -3, 25, 696, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 1339, 2, -4, 25, 696, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 1339, 2, -5, 25, 696, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 1339, 2, -6, 25, 696, -1, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 1339, 1, -3, 25, 696, -1, "", 1);// 359
			AddComplexComponent( (BaseAddon) this, 1339, 1, -4, 25, 696, -1, "", 1);// 360
			AddComplexComponent( (BaseAddon) this, 1339, 1, -5, 25, 696, -1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 1339, 1, -6, 25, 696, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 1339, 0, -2, 25, 696, -1, "", 1);// 363
			AddComplexComponent( (BaseAddon) this, 1339, 0, -3, 25, 696, -1, "", 1);// 364
			AddComplexComponent( (BaseAddon) this, 1339, 0, -4, 25, 696, -1, "", 1);// 365
			AddComplexComponent( (BaseAddon) this, 1339, 0, -5, 25, 696, -1, "", 1);// 366
			AddComplexComponent( (BaseAddon) this, 1339, 0, -6, 25, 696, -1, "", 1);// 367
			AddComplexComponent( (BaseAddon) this, 42, 3, -4, 5, 696, -1, "", 1);// 368
			AddComplexComponent( (BaseAddon) this, 43, 3, -5, 5, 696, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 1339, 4, -4, 5, 786, -1, "", 1);// 370
			AddComplexComponent( (BaseAddon) this, 1339, 4, -6, 5, 786, -1, "", 1);// 371
			AddComplexComponent( (BaseAddon) this, 10675, 0, -1, 5, 696, 1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 605, 0, 1, 5, 696, -1, "", 1);// 373
			AddComplexComponent( (BaseAddon) this, 10670, 2, -3, 5, 696, 1, "", 1);// 374
			AddComplexComponent( (BaseAddon) this, 612, 1, 1, 5, 696, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 606, 1, 0, 5, 696, -1, "", 1);// 376
			AddComplexComponent( (BaseAddon) this, 611, 1, -2, 5, 696, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 608, 4, -6, 5, 696, -1, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 605, 3, -2, 5, 696, -1, "", 1);// 379
			AddComplexComponent( (BaseAddon) this, 612, 4, -2, 5, 696, -1, "", 1);// 380
			AddComplexComponent( (BaseAddon) this, 604, 4, -3, 5, 696, -1, "", 1);// 381
			AddComplexComponent( (BaseAddon) this, 1339, 3, -6, 5, 786, -1, "", 1);// 382
			AddComplexComponent( (BaseAddon) this, 1339, 2, -6, 5, 786, -1, "", 1);// 383
			AddComplexComponent( (BaseAddon) this, 1339, 1, -6, 5, 786, -1, "", 1);// 384
			AddComplexComponent( (BaseAddon) this, 1339, 0, -6, 5, 786, -1, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 1339, 3, -2, 5, 786, -1, "", 1);// 386
			AddComplexComponent( (BaseAddon) this, 1339, 3, -3, 5, 786, -1, "", 1);// 387
			AddComplexComponent( (BaseAddon) this, 1339, 3, -4, 5, 786, -1, "", 1);// 388
			AddComplexComponent( (BaseAddon) this, 1339, 3, -5, 5, 786, -1, "", 1);// 389
			AddComplexComponent( (BaseAddon) this, 1339, 2, -3, 5, 786, -1, "", 1);// 390
			AddComplexComponent( (BaseAddon) this, 1339, 2, -4, 5, 786, -1, "", 1);// 391
			AddComplexComponent( (BaseAddon) this, 1339, 2, -5, 5, 786, -1, "", 1);// 392
			AddComplexComponent( (BaseAddon) this, 1339, 1, 1, 5, 786, -1, "", 1);// 393
			AddComplexComponent( (BaseAddon) this, 1339, 1, 0, 5, 786, -1, "", 1);// 394
			AddComplexComponent( (BaseAddon) this, 1339, 1, -2, 5, 786, -1, "", 1);// 395
			AddComplexComponent( (BaseAddon) this, 1339, 1, -3, 5, 786, -1, "", 1);// 396
			AddComplexComponent( (BaseAddon) this, 1339, 1, -4, 5, 786, -1, "", 1);// 397
			AddComplexComponent( (BaseAddon) this, 1339, 1, -5, 5, 786, -1, "", 1);// 398
			AddComplexComponent( (BaseAddon) this, 1339, 0, 1, 5, 786, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 1339, 0, 0, 5, 786, -1, "", 1);// 400
			AddComplexComponent( (BaseAddon) this, 1339, 0, -1, 5, 786, -1, "", 1);// 401
			AddComplexComponent( (BaseAddon) this, 1339, 0, -2, 5, 786, -1, "", 1);// 402
			AddComplexComponent( (BaseAddon) this, 1339, 0, -3, 5, 786, -1, "", 1);// 403
			AddComplexComponent( (BaseAddon) this, 1339, 0, -4, 5, 786, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 1339, 0, -5, 5, 786, -1, "", 1);// 405
			AddComplexComponent( (BaseAddon) this, 2272, 3, -7, 25, 696, -1, "", 1);// 406
			AddComplexComponent( (BaseAddon) this, 1339, 3, -7, 25, 696, -1, "", 1);// 407
			AddComplexComponent( (BaseAddon) this, 1339, 2, -7, 25, 696, -1, "", 1);// 408
			AddComplexComponent( (BaseAddon) this, 1339, 1, -7, 25, 696, -1, "", 1);// 409
			AddComplexComponent( (BaseAddon) this, 1339, 0, -7, 25, 696, -1, "", 1);// 410
			AddComplexComponent( (BaseAddon) this, 1339, 1, -7, 5, 786, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 10670, 1, -8, 5, 696, 1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 604, 4, -7, 5, 696, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 609, 2, -7, 5, 696, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 607, 0, -7, 5, 696, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 605, 3, -7, 5, 696, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 1339, -1, 0, 25, 696, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 1339, -1, -1, 25, 696, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 1339, -2, -2, 5, 786, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 2272, -2, 1, 27, 696, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 1339, -1, -2, 25, 696, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 1339, -1, -3, 25, 696, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1339, -1, -4, 25, 696, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 1339, -1, -5, 25, 696, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 1339, -1, -6, 25, 696, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 1339, -2, 0, 25, 696, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 1339, -2, -1, 25, 696, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 1339, -2, -2, 25, 696, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 1339, -2, -3, 25, 696, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 1339, -2, -4, 25, 696, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 1339, -2, -5, 25, 696, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 1339, -2, -6, 25, 696, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 10670, -1, 0, 5, 696, 1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 611, -2, 1, 5, 696, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 1339, -1, -6, 5, 786, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1339, -2, -6, 5, 786, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 1339, -1, 0, 5, 786, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 1339, -1, -1, 5, 786, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 1339, -1, -2, 5, 786, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 1339, -1, -3, 5, 786, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 1339, -1, -4, 5, 786, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 1339, -1, -5, 5, 786, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 1339, -2, 1, 5, 786, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 1339, -2, 0, 5, 786, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 1339, -2, -1, 5, 786, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 1339, -2, -3, 5, 786, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 1339, -2, -4, 5, 786, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 1339, -2, -5, 5, 786, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 2272, -2, -7, 25, 696, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 1339, -1, -7, 25, 696, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 1339, -2, -7, 25, 696, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 1339, -2, -7, 5, 786, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 10670, -2, -8, 5, 696, 1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 605, -1, -7, 5, 696, -1, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 1848, 6, 4, 0, 2404, -1, "", 1);// 470
			AddComplexComponent( (BaseAddon) this, 1848, 6, 3, 0, 2404, -1, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 1848, 6, 2, 0, 2404, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 1848, 6, 1, 0, 2404, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1848, 6, 0, 0, 2404, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 1848, 6, -1, 0, 2404, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 1848, 6, -2, 0, 2404, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 1848, 6, -3, 0, 2404, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 1848, 6, -4, 0, 2404, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 1848, 6, -5, 0, 2404, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1848, 6, -6, 0, 2404, -1, "", 1);// 480
			AddComplexComponent( (BaseAddon) this, 1848, 5, 4, 0, 2404, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 1848, 5, 3, 0, 2404, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 1848, 5, 2, 0, 2404, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 1848, 5, 1, 0, 2404, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 1848, 5, 0, 0, 2404, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 1848, 5, -1, 0, 2404, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1848, 5, -2, 0, 2404, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 1848, 5, -3, 0, 2404, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 1848, 5, -4, 0, 2404, -1, "", 1);// 489
			AddComplexComponent( (BaseAddon) this, 1848, 5, -5, 0, 2404, -1, "", 1);// 490
			AddComplexComponent( (BaseAddon) this, 1848, 5, -6, 0, 2404, -1, "", 1);// 491
			AddComplexComponent( (BaseAddon) this, 1848, 4, 4, 0, 2404, -1, "", 1);// 492
			AddComplexComponent( (BaseAddon) this, 1848, 4, 3, 0, 2404, -1, "", 1);// 493
			AddComplexComponent( (BaseAddon) this, 1848, 4, 2, 0, 2404, -1, "", 1);// 494
			AddComplexComponent( (BaseAddon) this, 1848, 4, 1, 0, 2404, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 1848, 4, 0, 0, 2404, -1, "", 1);// 496
			AddComplexComponent( (BaseAddon) this, 1848, 4, -1, 0, 2404, -1, "", 1);// 497
			AddComplexComponent( (BaseAddon) this, 1848, 4, -2, 0, 2404, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1848, 4, -3, 0, 2404, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1848, 4, -4, 0, 2404, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1848, 4, -5, 0, 2404, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1848, 4, -6, 0, 2404, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1848, 3, 4, 0, 2404, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1848, 3, 3, 0, 2404, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1848, 3, 2, 0, 2404, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1848, 3, 1, 0, 2404, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1848, 3, 0, 0, 2404, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1848, 3, -1, 0, 2404, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1848, 3, -2, 0, 2404, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1848, 3, -3, 0, 2404, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1848, 3, -4, 0, 2404, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1848, 3, -5, 0, 2404, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1848, 3, -6, 0, 2404, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1848, 2, 4, 0, 2404, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1848, 2, 3, 0, 2404, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1848, 2, 2, 0, 2404, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1848, 2, 1, 0, 2404, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1848, 2, 0, 0, 2404, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1848, 2, -1, 0, 2404, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1848, 2, -2, 0, 2404, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1848, 2, -3, 0, 2404, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1848, 2, -4, 0, 2404, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1848, 2, -5, 0, 2404, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1848, 2, -6, 0, 2404, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1848, 1, 4, 0, 2404, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1848, 1, 3, 0, 2404, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1848, 1, 2, 0, 2404, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1848, 1, 1, 0, 2404, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1848, 1, 0, 0, 2404, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1848, 1, -1, 0, 2404, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1848, 1, -2, 0, 2404, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1848, 1, -3, 0, 2404, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1848, 1, -4, 0, 2404, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1848, 1, -5, 0, 2404, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1848, 1, -6, 0, 2404, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1848, 0, 4, 0, 2404, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1848, 0, 3, 0, 2404, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 0, 2404, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 1848, 0, 1, 0, 2404, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1848, 0, 0, 0, 2404, -1, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 0, 2404, -1, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 0, 2404, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 1848, 0, -3, 0, 2404, -1, "", 1);// 543
			AddComplexComponent( (BaseAddon) this, 1848, 0, -4, 0, 2404, -1, "", 1);// 544
			AddComplexComponent( (BaseAddon) this, 1848, 0, -5, 0, 2404, -1, "", 1);// 545
			AddComplexComponent( (BaseAddon) this, 1848, 0, -6, 0, 2404, -1, "", 1);// 546
			AddComplexComponent( (BaseAddon) this, 1848, -1, 4, 0, 2404, -1, "", 1);// 547
			AddComplexComponent( (BaseAddon) this, 1848, -1, 3, 0, 2404, -1, "", 1);// 548
			AddComplexComponent( (BaseAddon) this, 1848, -1, 2, 0, 2404, -1, "", 1);// 549
			AddComplexComponent( (BaseAddon) this, 1848, -1, 1, 0, 2404, -1, "", 1);// 550
			AddComplexComponent( (BaseAddon) this, 1848, -1, 0, 0, 2404, -1, "", 1);// 551
			AddComplexComponent( (BaseAddon) this, 1848, -1, -1, 0, 2404, -1, "", 1);// 552
			AddComplexComponent( (BaseAddon) this, 1848, -1, -2, 0, 2404, -1, "", 1);// 553
			AddComplexComponent( (BaseAddon) this, 1848, -1, -3, 0, 2404, -1, "", 1);// 554
			AddComplexComponent( (BaseAddon) this, 1848, -1, -4, 0, 2404, -1, "", 1);// 555
			AddComplexComponent( (BaseAddon) this, 1848, -1, -5, 0, 2404, -1, "", 1);// 556
			AddComplexComponent( (BaseAddon) this, 1848, -1, -6, 0, 2404, -1, "", 1);// 557
			AddComplexComponent( (BaseAddon) this, 1848, -2, 4, 0, 2404, -1, "", 1);// 558
			AddComplexComponent( (BaseAddon) this, 1848, -2, 3, 0, 2404, -1, "", 1);// 559
			AddComplexComponent( (BaseAddon) this, 1848, -2, 2, 0, 2404, -1, "", 1);// 560
			AddComplexComponent( (BaseAddon) this, 1848, -2, 1, 0, 2404, -1, "", 1);// 561
			AddComplexComponent( (BaseAddon) this, 1848, -2, 0, 0, 2404, -1, "", 1);// 562
			AddComplexComponent( (BaseAddon) this, 1848, -2, -1, 0, 2404, -1, "", 1);// 563
			AddComplexComponent( (BaseAddon) this, 1848, -2, -2, 0, 2404, -1, "", 1);// 564
			AddComplexComponent( (BaseAddon) this, 1848, -2, -3, 0, 2404, -1, "", 1);// 565
			AddComplexComponent( (BaseAddon) this, 1848, -2, -4, 0, 2404, -1, "", 1);// 566
			AddComplexComponent( (BaseAddon) this, 1848, -2, -5, 0, 2404, -1, "", 1);// 567
			AddComplexComponent( (BaseAddon) this, 1848, -2, -6, 0, 2404, -1, "", 1);// 568
			AddComplexComponent( (BaseAddon) this, 1848, 7, 4, 0, 2404, -1, "", 1);// 569
			AddComplexComponent( (BaseAddon) this, 1848, 7, 3, 0, 2404, -1, "", 1);// 570
			AddComplexComponent( (BaseAddon) this, 1848, 7, 2, 0, 2404, -1, "", 1);// 571
			AddComplexComponent( (BaseAddon) this, 1848, 7, 1, 0, 2404, -1, "", 1);// 572
			AddComplexComponent( (BaseAddon) this, 1848, 7, 0, 0, 2404, -1, "", 1);// 573
			AddComplexComponent( (BaseAddon) this, 1848, 7, -1, 0, 2404, -1, "", 1);// 574
			AddComplexComponent( (BaseAddon) this, 1848, 7, -2, 0, 2404, -1, "", 1);// 575
			AddComplexComponent( (BaseAddon) this, 1848, 7, -3, 0, 2404, -1, "", 1);// 576
			AddComplexComponent( (BaseAddon) this, 1848, 7, -4, 0, 2404, -1, "", 1);// 577
			AddComplexComponent( (BaseAddon) this, 1848, 7, -5, 0, 2404, -1, "", 1);// 578
			AddComplexComponent( (BaseAddon) this, 1848, 7, -6, 0, 2404, -1, "", 1);// 579
			AddComplexComponent( (BaseAddon) this, 1848, 7, -7, 0, 2404, -1, "", 1);// 580
			AddComplexComponent( (BaseAddon) this, 1848, 6, -7, 0, 2404, -1, "", 1);// 581
			AddComplexComponent( (BaseAddon) this, 1848, 5, -7, 0, 2404, -1, "", 1);// 582
			AddComplexComponent( (BaseAddon) this, 1848, 4, -7, 0, 2404, -1, "", 1);// 583
			AddComplexComponent( (BaseAddon) this, 1848, 3, -7, 0, 2404, -1, "", 1);// 584
			AddComplexComponent( (BaseAddon) this, 1848, 2, -7, 0, 2404, -1, "", 1);// 585
			AddComplexComponent( (BaseAddon) this, 1848, 1, -7, 0, 2404, -1, "", 1);// 586
			AddComplexComponent( (BaseAddon) this, 1848, 0, -7, 0, 2404, -1, "", 1);// 587
			AddComplexComponent( (BaseAddon) this, 1848, -1, -7, 0, 2404, -1, "", 1);// 588
			AddComplexComponent( (BaseAddon) this, 1848, -2, -7, 0, 2404, -1, "", 1);// 589
			AddComplexComponent( (BaseAddon) this, 1339, -4, 7, 5, 786, -1, "", 1);// 603
			AddComplexComponent( (BaseAddon) this, 1339, -4, 6, 5, 786, -1, "", 1);// 604
			AddComplexComponent( (BaseAddon) this, 1339, -4, 5, 5, 786, -1, "", 1);// 605
			AddComplexComponent( (BaseAddon) this, 1339, -5, 7, 5, 786, -1, "", 1);// 606
			AddComplexComponent( (BaseAddon) this, 1339, -5, 6, 5, 786, -1, "", 1);// 607
			AddComplexComponent( (BaseAddon) this, 1339, -5, 5, 5, 786, -1, "", 1);// 608
			AddComplexComponent( (BaseAddon) this, 1849, -4, 8, 0, 696, -1, "", 1);// 609
			AddComplexComponent( (BaseAddon) this, 1849, -5, 8, 0, 696, -1, "", 1);// 610
			AddComplexComponent( (BaseAddon) this, 2273, -8, 7, 0, 696, -1, "", 1);// 611
			AddComplexComponent( (BaseAddon) this, 2273, -8, 6, 0, 696, -1, "", 1);// 612
			AddComplexComponent( (BaseAddon) this, 2273, -8, 5, 0, 696, -1, "", 1);// 613
			AddComplexComponent( (BaseAddon) this, 2273, -6, 8, 0, 696, -1, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 2273, -3, 8, 0, 696, -1, "", 1);// 615
			AddComplexComponent( (BaseAddon) this, 2273, -7, 8, 0, 696, -1, "", 1);// 616
			AddComplexComponent( (BaseAddon) this, 2273, -8, 8, 0, 696, -1, "", 1);// 617
			AddComplexComponent( (BaseAddon) this, 628, -8, 7, 5, 696, -1, "", 1);// 618
			AddComplexComponent( (BaseAddon) this, 628, -8, 6, 5, 696, -1, "", 1);// 619
			AddComplexComponent( (BaseAddon) this, 628, -8, 5, 5, 696, -1, "", 1);// 620
			AddComplexComponent( (BaseAddon) this, 624, -3, 7, 5, 696, -1, "", 1);// 621
			AddComplexComponent( (BaseAddon) this, 624, -4, 7, 5, 696, -1, "", 1);// 622
			AddComplexComponent( (BaseAddon) this, 624, -5, 7, 5, 696, -1, "", 1);// 623
			AddComplexComponent( (BaseAddon) this, 624, -6, 7, 5, 696, -1, "", 1);// 624
			AddComplexComponent( (BaseAddon) this, 624, -7, 7, 5, 696, -1, "", 1);// 625
			AddComplexComponent( (BaseAddon) this, 1848, -3, 7, 0, 2404, -1, "", 1);// 635
			AddComplexComponent( (BaseAddon) this, 1848, -3, 6, 0, 2404, -1, "", 1);// 636
			AddComplexComponent( (BaseAddon) this, 1848, -3, 5, 0, 2404, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1848, -4, 7, 0, 2404, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 1848, -4, 6, 0, 2404, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 1848, -4, 5, 0, 2404, -1, "", 1);// 640
			AddComplexComponent( (BaseAddon) this, 1848, -5, 7, 0, 2404, -1, "", 1);// 641
			AddComplexComponent( (BaseAddon) this, 1848, -5, 6, 0, 2404, -1, "", 1);// 642
			AddComplexComponent( (BaseAddon) this, 1848, -5, 5, 0, 2404, -1, "", 1);// 643
			AddComplexComponent( (BaseAddon) this, 1848, -6, 7, 0, 2404, -1, "", 1);// 644
			AddComplexComponent( (BaseAddon) this, 1848, -6, 6, 0, 2404, -1, "", 1);// 645
			AddComplexComponent( (BaseAddon) this, 1848, -6, 5, 0, 2404, -1, "", 1);// 646
			AddComplexComponent( (BaseAddon) this, 1848, -7, 7, 0, 2404, -1, "", 1);// 647
			AddComplexComponent( (BaseAddon) this, 1848, -7, 6, 0, 2404, -1, "", 1);// 648
			AddComplexComponent( (BaseAddon) this, 1848, -7, 5, 0, 2404, -1, "", 1);// 649
			AddComplexComponent( (BaseAddon) this, 3231, -3, -3, 49, 1368, -1, "", 1);// 656
			AddComplexComponent( (BaseAddon) this, 3231, -7, -7, 47, 1368, -1, "", 1);// 657
			AddComplexComponent( (BaseAddon) this, 3231, -6, -2, 48, 1368, -1, "", 1);// 658
			AddComplexComponent( (BaseAddon) this, 3231, -7, 1, 26, 1368, -1, "", 1);// 659
			AddComplexComponent( (BaseAddon) this, 2279, -5, -7, 47, 696, -1, "", 1);// 660
			AddComplexComponent( (BaseAddon) this, 2279, -7, -5, 47, 696, -1, "", 1);// 661
			AddComplexComponent( (BaseAddon) this, 2279, -3, -2, 47, 696, -1, "", 1);// 662
			AddComplexComponent( (BaseAddon) this, 2279, -7, -2, 47, 696, -1, "", 1);// 663
			AddComplexComponent( (BaseAddon) this, 2281, -4, 3, 25, 696, -1, "", 1);// 664
			AddComplexComponent( (BaseAddon) this, 2276, -7, 2, 25, 696, -1, "", 1);// 665
			AddComplexComponent( (BaseAddon) this, 2276, -7, 0, 25, 696, -1, "", 1);// 666
			AddComplexComponent( (BaseAddon) this, 47, -4, -2, 45, 696, -1, "", 1);// 667
			AddComplexComponent( (BaseAddon) this, 47, -6, -2, 45, 696, -1, "", 1);// 668
			AddComplexComponent( (BaseAddon) this, 628, -8, -2, 49, 696, -1, "", 1);// 669
			AddComplexComponent( (BaseAddon) this, 628, -8, -3, 49, 696, -1, "", 1);// 670
			AddComplexComponent( (BaseAddon) this, 628, -8, -4, 49, 696, -1, "", 1);// 671
			AddComplexComponent( (BaseAddon) this, 628, -8, -5, 49, 696, -1, "", 1);// 672
			AddComplexComponent( (BaseAddon) this, 628, -8, -6, 49, 696, -1, "", 1);// 673
			AddComplexComponent( (BaseAddon) this, 628, -8, -7, 49, 696, -1, "", 1);// 674
			AddComplexComponent( (BaseAddon) this, 624, -3, -8, 49, 696, -1, "", 1);// 675
			AddComplexComponent( (BaseAddon) this, 624, -4, -8, 49, 696, -1, "", 1);// 676
			AddComplexComponent( (BaseAddon) this, 624, -5, -8, 49, 696, -1, "", 1);// 677
			AddComplexComponent( (BaseAddon) this, 624, -6, -8, 49, 696, -1, "", 1);// 678
			AddComplexComponent( (BaseAddon) this, 624, -7, -8, 49, 696, -1, "", 1);// 679
			AddComplexComponent( (BaseAddon) this, 624, -4, -2, 49, 696, -1, "", 1);// 680
			AddComplexComponent( (BaseAddon) this, 624, -5, -2, 49, 696, -1, "", 1);// 681
			AddComplexComponent( (BaseAddon) this, 624, -6, -2, 49, 696, -1, "", 1);// 682
			AddComplexComponent( (BaseAddon) this, 624, -7, -2, 49, 696, -1, "", 1);// 683
			AddComplexComponent( (BaseAddon) this, 625, -3, -2, 50, 696, -1, "", 1);// 684
			AddComplexComponent( (BaseAddon) this, 48, -3, -3, 47, 696, -1, "", 1);// 685
			AddComplexComponent( (BaseAddon) this, 48, -8, -8, 47, 696, -1, "", 1);// 686
			AddComplexComponent( (BaseAddon) this, 47, -4, -2, 47, 696, -1, "", 1);// 687
			AddComplexComponent( (BaseAddon) this, 47, -5, -2, 47, 696, -1, "", 1);// 688
			AddComplexComponent( (BaseAddon) this, 47, -6, -2, 47, 696, -1, "", 1);// 689
			AddComplexComponent( (BaseAddon) this, 47, -7, -2, 47, 696, -1, "", 1);// 690
			AddComplexComponent( (BaseAddon) this, 47, -3, -8, 47, 696, -1, "", 1);// 691
			AddComplexComponent( (BaseAddon) this, 47, -4, -8, 47, 696, -1, "", 1);// 692
			AddComplexComponent( (BaseAddon) this, 47, -5, -8, 47, 696, -1, "", 1);// 693
			AddComplexComponent( (BaseAddon) this, 47, -6, -8, 47, 696, -1, "", 1);// 694
			AddComplexComponent( (BaseAddon) this, 47, -7, -8, 47, 696, -1, "", 1);// 695
			AddComplexComponent( (BaseAddon) this, 46, -8, -2, 47, 696, -1, "", 1);// 696
			AddComplexComponent( (BaseAddon) this, 46, -8, -3, 47, 696, -1, "", 1);// 697
			AddComplexComponent( (BaseAddon) this, 46, -8, -4, 47, 696, -1, "", 1);// 698
			AddComplexComponent( (BaseAddon) this, 46, -8, -5, 47, 696, -1, "", 1);// 699
			AddComplexComponent( (BaseAddon) this, 46, -8, -6, 47, 696, -1, "", 1);// 700
			AddComplexComponent( (BaseAddon) this, 46, -8, -7, 47, 696, -1, "", 1);// 701
			AddComplexComponent( (BaseAddon) this, 45, -3, -2, 47, 696, -1, "", 1);// 702
			AddComplexComponent( (BaseAddon) this, 1339, -3, -2, 47, 696, -1, "", 1);// 703
			AddComplexComponent( (BaseAddon) this, 1339, -3, -3, 47, 696, -1, "", 1);// 704
			AddComplexComponent( (BaseAddon) this, 1339, -3, -4, 47, 696, -1, "", 1);// 705
			AddComplexComponent( (BaseAddon) this, 1339, -3, -5, 47, 696, -1, "", 1);// 706
			AddComplexComponent( (BaseAddon) this, 1339, -3, -6, 47, 696, -1, "", 1);// 707
			AddComplexComponent( (BaseAddon) this, 1339, -3, -7, 47, 696, -1, "", 1);// 708
			AddComplexComponent( (BaseAddon) this, 1339, -4, -2, 47, 696, -1, "", 1);// 709
			AddComplexComponent( (BaseAddon) this, 1339, -4, -3, 47, 696, -1, "", 1);// 710
			AddComplexComponent( (BaseAddon) this, 1339, -4, -4, 47, 696, -1, "", 1);// 711
			AddComplexComponent( (BaseAddon) this, 1339, -4, -5, 47, 696, -1, "", 1);// 712
			AddComplexComponent( (BaseAddon) this, 1339, -4, -6, 47, 696, -1, "", 1);// 713
			AddComplexComponent( (BaseAddon) this, 1339, -4, -7, 47, 696, -1, "", 1);// 714
			AddComplexComponent( (BaseAddon) this, 1339, -5, -2, 47, 696, -1, "", 1);// 715
			AddComplexComponent( (BaseAddon) this, 1339, -5, -3, 47, 696, -1, "", 1);// 716
			AddComplexComponent( (BaseAddon) this, 1339, -5, -4, 47, 696, -1, "", 1);// 717
			AddComplexComponent( (BaseAddon) this, 1339, -5, -5, 47, 696, -1, "", 1);// 718
			AddComplexComponent( (BaseAddon) this, 1339, -5, -6, 47, 696, -1, "", 1);// 719
			AddComplexComponent( (BaseAddon) this, 1339, -5, -7, 47, 696, -1, "", 1);// 720
			AddComplexComponent( (BaseAddon) this, 1339, -6, -2, 47, 696, -1, "", 1);// 721
			AddComplexComponent( (BaseAddon) this, 1339, -6, -3, 47, 696, -1, "", 1);// 722
			AddComplexComponent( (BaseAddon) this, 1339, -6, -4, 47, 696, -1, "", 1);// 723
			AddComplexComponent( (BaseAddon) this, 1339, -6, -5, 47, 696, -1, "", 1);// 724
			AddComplexComponent( (BaseAddon) this, 1339, -6, -6, 47, 696, -1, "", 1);// 725
			AddComplexComponent( (BaseAddon) this, 1339, -6, -7, 47, 696, -1, "", 1);// 726
			AddComplexComponent( (BaseAddon) this, 1339, -7, -2, 47, 696, -1, "", 1);// 727
			AddComplexComponent( (BaseAddon) this, 1339, -7, -3, 47, 696, -1, "", 1);// 728
			AddComplexComponent( (BaseAddon) this, 1339, -7, -4, 47, 696, -1, "", 1);// 729
			AddComplexComponent( (BaseAddon) this, 1339, -7, -5, 47, 696, -1, "", 1);// 730
			AddComplexComponent( (BaseAddon) this, 1339, -7, -6, 47, 696, -1, "", 1);// 731
			AddComplexComponent( (BaseAddon) this, 1339, -7, -7, 47, 696, -1, "", 1);// 732
			AddComplexComponent( (BaseAddon) this, 1339, -7, -7, 47, 786, -1, "", 1);// 733
			AddComplexComponent( (BaseAddon) this, 44, -6, -2, 25, 696, -1, "", 1);// 734
			AddComplexComponent( (BaseAddon) this, 41, -4, -2, 25, 696, -1, "", 1);// 735
			AddComplexComponent( (BaseAddon) this, 605, -7, -1, 25, 696, -1, "", 1);// 736
			AddComplexComponent( (BaseAddon) this, 605, -3, -1, 25, 696, -1, "", 1);// 737
			AddComplexComponent( (BaseAddon) this, 604, -7, -2, 25, 696, -1, "", 1);// 738
			AddComplexComponent( (BaseAddon) this, 610, -7, -7, 25, 696, -1, "", 1);// 739
			AddComplexComponent( (BaseAddon) this, 1339, -5, -5, 25, 696, -1, "", 1);// 740
			AddComplexComponent( (BaseAddon) this, 1339, -6, -5, 25, 696, -1, "", 1);// 741
			AddComplexComponent( (BaseAddon) this, 606, -7, -3, 25, 696, -1, "", 1);// 742
			AddComplexComponent( (BaseAddon) this, 606, -7, -4, 25, 696, -1, "", 1);// 743
			AddComplexComponent( (BaseAddon) this, 606, -7, -5, 25, 696, -1, "", 1);// 744
			AddComplexComponent( (BaseAddon) this, 606, -7, -6, 25, 696, -1, "", 1);// 745
			AddComplexComponent( (BaseAddon) this, 605, -3, -7, 25, 696, -1, "", 1);// 746
			AddComplexComponent( (BaseAddon) this, 605, -4, -7, 25, 696, -1, "", 1);// 747
			AddComplexComponent( (BaseAddon) this, 605, -5, -7, 25, 696, -1, "", 1);// 748
			AddComplexComponent( (BaseAddon) this, 605, -6, -7, 25, 696, -1, "", 1);// 749
			AddComplexComponent( (BaseAddon) this, 47, -4, 3, 25, 696, -1, "", 1);// 750
			AddComplexComponent( (BaseAddon) this, 47, -5, 3, 25, 696, -1, "", 1);// 751
			AddComplexComponent( (BaseAddon) this, 46, -3, 2, 25, 696, -1, "", 1);// 752
			AddComplexComponent( (BaseAddon) this, 1339, -5, 4, 5, 786, -1, "", 1);// 753
			AddComplexComponent( (BaseAddon) this, 1339, -6, 4, 5, 786, -1, "", 1);// 754
			AddComplexComponent( (BaseAddon) this, 1339, -4, 4, 5, 786, -1, "", 1);// 755
			AddComplexComponent( (BaseAddon) this, 609, -6, 4, 5, 696, -1, "", 1);// 756
			AddComplexComponent( (BaseAddon) this, 605, -3, 4, 5, 696, -1, "", 1);// 757
			AddComplexComponent( (BaseAddon) this, 605, -7, 4, 5, 696, -1, "", 1);// 758
			AddComplexComponent( (BaseAddon) this, 2272, -3, 3, 25, 696, -1, "", 1);// 759
			AddComplexComponent( (BaseAddon) this, 1339, -3, 3, 25, 696, -1, "", 1);// 760
			AddComplexComponent( (BaseAddon) this, 1339, -3, 2, 25, 696, -1, "", 1);// 761
			AddComplexComponent( (BaseAddon) this, 1339, -3, 1, 25, 696, -1, "", 1);// 762
			AddComplexComponent( (BaseAddon) this, 1339, -3, 0, 25, 696, -1, "", 1);// 763
			AddComplexComponent( (BaseAddon) this, 1339, -3, -1, 25, 696, -1, "", 1);// 764
			AddComplexComponent( (BaseAddon) this, 1339, -3, -2, 25, 696, -1, "", 1);// 765
			AddComplexComponent( (BaseAddon) this, 1339, -3, -3, 25, 696, -1, "", 1);// 766
			AddComplexComponent( (BaseAddon) this, 1339, -3, -4, 25, 696, -1, "", 1);// 767
			AddComplexComponent( (BaseAddon) this, 1339, -3, -5, 25, 696, -1, "", 1);// 768
			AddComplexComponent( (BaseAddon) this, 1339, -3, -6, 25, 696, -1, "", 1);// 769
			AddComplexComponent( (BaseAddon) this, 10675, -3, 2, 5, 696, 1, "", 1);// 770
			AddComplexComponent( (BaseAddon) this, 1339, -3, -6, 5, 786, -1, "", 1);// 771
			AddComplexComponent( (BaseAddon) this, 1339, -3, 3, 5, 786, -1, "", 1);// 772
			AddComplexComponent( (BaseAddon) this, 1339, -3, 2, 5, 786, -1, "", 1);// 773
			AddComplexComponent( (BaseAddon) this, 1339, -3, 1, 5, 786, -1, "", 1);// 774
			AddComplexComponent( (BaseAddon) this, 1339, -3, 0, 5, 786, -1, "", 1);// 775
			AddComplexComponent( (BaseAddon) this, 1339, -3, -1, 5, 786, -1, "", 1);// 776
			AddComplexComponent( (BaseAddon) this, 1339, -3, -2, 5, 786, -1, "", 1);// 777
			AddComplexComponent( (BaseAddon) this, 1339, -3, -3, 5, 786, -1, "", 1);// 778
			AddComplexComponent( (BaseAddon) this, 1339, -3, -4, 5, 786, -1, "", 1);// 779
			AddComplexComponent( (BaseAddon) this, 1339, -3, -5, 5, 786, -1, "", 1);// 780
			AddComplexComponent( (BaseAddon) this, 1339, -3, -7, 25, 696, -1, "", 1);// 781
			AddComplexComponent( (BaseAddon) this, 607, -3, -7, 5, 696, -1, "", 1);// 782
			AddComplexComponent( (BaseAddon) this, 2273, -8, 4, 0, 696, -1, "", 1);// 783
			AddComplexComponent( (BaseAddon) this, 2273, -8, 3, 0, 696, -1, "", 1);// 784
			AddComplexComponent( (BaseAddon) this, 628, -8, 4, 5, 696, -1, "", 1);// 785
			AddComplexComponent( (BaseAddon) this, 2272, -7, 3, 25, 696, -1, "", 1);// 787
			AddComplexComponent( (BaseAddon) this, 1339, -4, 3, 25, 696, -1, "", 1);// 788
			AddComplexComponent( (BaseAddon) this, 1339, -5, 3, 25, 696, -1, "", 1);// 789
			AddComplexComponent( (BaseAddon) this, 1339, -6, 3, 25, 696, -1, "", 1);// 790
			AddComplexComponent( (BaseAddon) this, 1339, -7, 3, 25, 696, -1, "", 1);// 791
			AddComplexComponent( (BaseAddon) this, 44, -5, 3, 5, 696, -1, "", 1);// 792
			AddComplexComponent( (BaseAddon) this, 41, -4, 3, 5, 696, -1, "", 1);// 793
			AddComplexComponent( (BaseAddon) this, 608, -7, 3, 5, 696, -1, "", 1);// 794
			AddComplexComponent( (BaseAddon) this, 1339, -6, 3, 5, 786, -1, "", 1);// 795
			AddComplexComponent( (BaseAddon) this, 1339, -4, 3, 5, 786, -1, "", 1);// 796
			AddComplexComponent( (BaseAddon) this, 1339, -5, 3, 5, 786, -1, "", 1);// 797
			AddComplexComponent( (BaseAddon) this, 1339, -4, 2, 25, 696, -1, "", 1);// 798
			AddComplexComponent( (BaseAddon) this, 1339, -4, 1, 25, 696, -1, "", 1);// 799
			AddComplexComponent( (BaseAddon) this, 1339, -4, 0, 25, 696, -1, "", 1);// 800
			AddComplexComponent( (BaseAddon) this, 1339, -4, -1, 25, 696, -1, "", 1);// 801
			AddComplexComponent( (BaseAddon) this, 1339, -4, -2, 25, 696, -1, "", 1);// 802
			AddComplexComponent( (BaseAddon) this, 1339, -4, -3, 25, 696, -1, "", 1);// 803
			AddComplexComponent( (BaseAddon) this, 1339, -4, -4, 25, 696, -1, "", 1);// 804
			AddComplexComponent( (BaseAddon) this, 1339, -4, -6, 25, 696, -1, "", 1);// 805
			AddComplexComponent( (BaseAddon) this, 1339, -4, -6, 5, 786, -1, "", 1);// 806
			AddComplexComponent( (BaseAddon) this, 1339, -4, 2, 5, 786, -1, "", 1);// 807
			AddComplexComponent( (BaseAddon) this, 1339, -4, 1, 5, 786, -1, "", 1);// 808
			AddComplexComponent( (BaseAddon) this, 1339, -4, 0, 5, 786, -1, "", 1);// 809
			AddComplexComponent( (BaseAddon) this, 1339, -4, -1, 5, 786, -1, "", 1);// 810
			AddComplexComponent( (BaseAddon) this, 1339, -4, -2, 5, 786, -1, "", 1);// 811
			AddComplexComponent( (BaseAddon) this, 1339, -4, -3, 5, 786, -1, "", 1);// 812
			AddComplexComponent( (BaseAddon) this, 1339, -4, -4, 5, 786, -1, "", 1);// 813
			AddComplexComponent( (BaseAddon) this, 1339, -4, -5, 5, 786, -1, "", 1);// 814
			AddComplexComponent( (BaseAddon) this, 1339, -4, -7, 25, 696, -1, "", 1);// 815
			AddComplexComponent( (BaseAddon) this, 26, -4, -7, 5, 696, -1, "", 1);// 816
			AddComplexComponent( (BaseAddon) this, 27, -4, -7, 5, 696, -1, "", 1);// 817
			AddComplexComponent( (BaseAddon) this, 607, -4, -7, 5, 696, -1, "", 1);// 818
			AddComplexComponent( (BaseAddon) this, 1339, -4, -5, 25, 696, -1, "", 1);// 819
			AddComplexComponent( (BaseAddon) this, 1339, -5, 2, 25, 696, -1, "", 1);// 820
			AddComplexComponent( (BaseAddon) this, 1339, -6, 2, 25, 696, -1, "", 1);// 821
			AddComplexComponent( (BaseAddon) this, 1339, -7, 2, 25, 696, -1, "", 1);// 822
			AddComplexComponent( (BaseAddon) this, 604, -7, 2, 5, 696, -1, "", 1);// 823
			AddComplexComponent( (BaseAddon) this, 1339, -6, 2, 5, 786, -1, "", 1);// 824
			AddComplexComponent( (BaseAddon) this, 1339, -5, 2, 5, 786, -1, "", 1);// 825
			AddComplexComponent( (BaseAddon) this, 1339, -5, 1, 25, 696, -1, "", 1);// 826
			AddComplexComponent( (BaseAddon) this, 1339, -5, 0, 25, 696, -1, "", 1);// 827
			AddComplexComponent( (BaseAddon) this, 1339, -5, -1, 25, 696, -1, "", 1);// 828
			AddComplexComponent( (BaseAddon) this, 1339, -5, -2, 25, 696, -1, "", 1);// 829
			AddComplexComponent( (BaseAddon) this, 1339, -5, -3, 25, 696, -1, "", 1);// 830
			AddComplexComponent( (BaseAddon) this, 1339, -5, -6, 25, 696, -1, "", 1);// 831
			AddComplexComponent( (BaseAddon) this, 1339, -5, -6, 5, 786, -1, "", 1);// 832
			AddComplexComponent( (BaseAddon) this, 1339, -5, 1, 5, 786, -1, "", 1);// 833
			AddComplexComponent( (BaseAddon) this, 1339, -5, 0, 5, 786, -1, "", 1);// 834
			AddComplexComponent( (BaseAddon) this, 1339, -5, -1, 5, 786, -1, "", 1);// 835
			AddComplexComponent( (BaseAddon) this, 1339, -5, -2, 5, 786, -1, "", 1);// 836
			AddComplexComponent( (BaseAddon) this, 1339, -5, -3, 5, 786, -1, "", 1);// 837
			AddComplexComponent( (BaseAddon) this, 1339, -5, -4, 5, 786, -1, "", 1);// 838
			AddComplexComponent( (BaseAddon) this, 1339, -5, -5, 5, 786, -1, "", 1);// 839
			AddComplexComponent( (BaseAddon) this, 1339, -5, -7, 25, 696, -1, "", 1);// 840
			AddComplexComponent( (BaseAddon) this, 49, -5, -7, 5, 696, -1, "", 1);// 841
			AddComplexComponent( (BaseAddon) this, 6571, -5, -7, 9, 0, 0, "", 1);// 842
			AddComplexComponent( (BaseAddon) this, 3555, -5, -7, 10, 0, 0, "", 1);// 843
			AddComplexComponent( (BaseAddon) this, 37, -5, -7, 15, 696, -1, "", 1);// 844
			AddComplexComponent( (BaseAddon) this, 609, -5, -7, 5, 696, -1, "", 1);// 845
			AddComplexComponent( (BaseAddon) this, 1339, -5, -4, 25, 696, -1, "", 1);// 846
			AddComplexComponent( (BaseAddon) this, 2272, -7, -2, 25, 696, -1, "", 1);// 848
			AddComplexComponent( (BaseAddon) this, 1339, -6, 1, 25, 696, -1, "", 1);// 849
			AddComplexComponent( (BaseAddon) this, 1339, -6, 0, 25, 696, -1, "", 1);// 850
			AddComplexComponent( (BaseAddon) this, 1339, -6, -1, 25, 696, -1, "", 1);// 851
			AddComplexComponent( (BaseAddon) this, 1339, -6, -2, 25, 696, -1, "", 1);// 852
			AddComplexComponent( (BaseAddon) this, 1339, -6, -3, 25, 696, -1, "", 1);// 853
			AddComplexComponent( (BaseAddon) this, 1339, -6, -4, 25, 696, -1, "", 1);// 854
			AddComplexComponent( (BaseAddon) this, 1339, -6, -6, 25, 696, -1, "", 1);// 855
			AddComplexComponent( (BaseAddon) this, 1339, -7, 1, 25, 696, -1, "", 1);// 856
			AddComplexComponent( (BaseAddon) this, 1339, -7, 0, 25, 696, -1, "", 1);// 857
			AddComplexComponent( (BaseAddon) this, 1339, -7, -1, 25, 696, -1, "", 1);// 858
			AddComplexComponent( (BaseAddon) this, 1339, -7, -2, 25, 696, -1, "", 1);// 859
			AddComplexComponent( (BaseAddon) this, 1339, -7, -3, 25, 696, -1, "", 1);// 860
			AddComplexComponent( (BaseAddon) this, 1339, -7, -4, 25, 696, -1, "", 1);// 861
			AddComplexComponent( (BaseAddon) this, 1339, -7, -5, 25, 696, -1, "", 1);// 862
			AddComplexComponent( (BaseAddon) this, 1339, -7, -6, 25, 696, -1, "", 1);// 863
			AddComplexComponent( (BaseAddon) this, 1339, -7, -2, 5, 786, -1, "", 1);// 864
			AddComplexComponent( (BaseAddon) this, 10675, -8, -2, 5, 696, 1, "", 1);// 865
			AddComplexComponent( (BaseAddon) this, 1339, -7, 1, 5, 786, -1, "", 1);// 866
			AddComplexComponent( (BaseAddon) this, 10675, -8, 1, 5, 696, 1, "", 1);// 867
			AddComplexComponent( (BaseAddon) this, 608, -7, 0, 5, 696, -1, "", 1);// 868
			AddComplexComponent( (BaseAddon) this, 606, -7, -1, 5, 696, -1, "", 1);// 869
			AddComplexComponent( (BaseAddon) this, 604, -7, -3, 5, 696, -1, "", 1);// 870
			AddComplexComponent( (BaseAddon) this, 608, -7, -4, 5, 696, -1, "", 1);// 871
			AddComplexComponent( (BaseAddon) this, 606, -7, -5, 5, 696, -1, "", 1);// 872
			AddComplexComponent( (BaseAddon) this, 604, -7, -6, 5, 696, -1, "", 1);// 873
			AddComplexComponent( (BaseAddon) this, 1339, -6, 1, 5, 786, -1, "", 1);// 874
			AddComplexComponent( (BaseAddon) this, 1339, -6, 0, 5, 786, -1, "", 1);// 875
			AddComplexComponent( (BaseAddon) this, 1339, -6, -1, 5, 786, -1, "", 1);// 876
			AddComplexComponent( (BaseAddon) this, 1339, -6, -2, 5, 786, -1, "", 1);// 877
			AddComplexComponent( (BaseAddon) this, 1339, -6, -3, 5, 786, -1, "", 1);// 878
			AddComplexComponent( (BaseAddon) this, 1339, -6, -4, 5, 786, -1, "", 1);// 879
			AddComplexComponent( (BaseAddon) this, 1339, -6, -5, 5, 786, -1, "", 1);// 880
			AddComplexComponent( (BaseAddon) this, 1339, -6, -6, 5, 786, -1, "", 1);// 881
			AddComplexComponent( (BaseAddon) this, 2272, -7, -7, 27, 696, -1, "", 1);// 882
			AddComplexComponent( (BaseAddon) this, 1339, -6, -7, 25, 696, -1, "", 1);// 883
			AddComplexComponent( (BaseAddon) this, 1339, -7, -7, 25, 696, -1, "", 1);// 884
			AddComplexComponent( (BaseAddon) this, 6571, -6, -7, 5, 0, 0, "", 1);// 885
			AddComplexComponent( (BaseAddon) this, 37, -6, -8, 5, 696, -1, "", 1);// 886
			AddComplexComponent( (BaseAddon) this, 27, -6, -7, 5, 696, -1, "", 1);// 887
			AddComplexComponent( (BaseAddon) this, 605, -6, -7, 5, 696, -1, "", 1);// 888
			AddComplexComponent( (BaseAddon) this, 611, -7, -7, 5, 696, -1, "", 1);// 889
			AddComplexComponent( (BaseAddon) this, 1848, -3, 4, 0, 2404, -1, "", 1);// 890
			AddComplexComponent( (BaseAddon) this, 1848, -3, 3, 0, 2404, -1, "", 1);// 891
			AddComplexComponent( (BaseAddon) this, 1848, -3, 2, 0, 2404, -1, "", 1);// 892
			AddComplexComponent( (BaseAddon) this, 1848, -3, 1, 0, 2404, -1, "", 1);// 893
			AddComplexComponent( (BaseAddon) this, 1848, -3, 0, 0, 2404, -1, "", 1);// 894
			AddComplexComponent( (BaseAddon) this, 1848, -3, -1, 0, 2404, -1, "", 1);// 895
			AddComplexComponent( (BaseAddon) this, 1848, -3, -2, 0, 2404, -1, "", 1);// 896
			AddComplexComponent( (BaseAddon) this, 1848, -3, -3, 0, 2404, -1, "", 1);// 897
			AddComplexComponent( (BaseAddon) this, 1848, -3, -4, 0, 2404, -1, "", 1);// 898
			AddComplexComponent( (BaseAddon) this, 1848, -3, -5, 0, 2404, -1, "", 1);// 899
			AddComplexComponent( (BaseAddon) this, 1848, -3, -6, 0, 2404, -1, "", 1);// 900
			AddComplexComponent( (BaseAddon) this, 1848, -4, 4, 0, 2404, -1, "", 1);// 901
			AddComplexComponent( (BaseAddon) this, 1848, -4, 3, 0, 2404, -1, "", 1);// 902
			AddComplexComponent( (BaseAddon) this, 1848, -4, 2, 0, 2404, -1, "", 1);// 903
			AddComplexComponent( (BaseAddon) this, 1848, -4, 1, 0, 2404, -1, "", 1);// 904
			AddComplexComponent( (BaseAddon) this, 1848, -4, 0, 0, 2404, -1, "", 1);// 905
			AddComplexComponent( (BaseAddon) this, 1848, -4, -1, 0, 2404, -1, "", 1);// 906
			AddComplexComponent( (BaseAddon) this, 1848, -4, -2, 0, 2404, -1, "", 1);// 907
			AddComplexComponent( (BaseAddon) this, 1848, -4, -3, 0, 2404, -1, "", 1);// 908
			AddComplexComponent( (BaseAddon) this, 1848, -4, -4, 0, 2404, -1, "", 1);// 909
			AddComplexComponent( (BaseAddon) this, 1848, -4, -5, 0, 2404, -1, "", 1);// 910
			AddComplexComponent( (BaseAddon) this, 1848, -4, -6, 0, 2404, -1, "", 1);// 911
			AddComplexComponent( (BaseAddon) this, 1848, -5, 4, 0, 2404, -1, "", 1);// 912
			AddComplexComponent( (BaseAddon) this, 1848, -5, 3, 0, 2404, -1, "", 1);// 913
			AddComplexComponent( (BaseAddon) this, 1848, -5, 2, 0, 2404, -1, "", 1);// 914
			AddComplexComponent( (BaseAddon) this, 1848, -5, 1, 0, 2404, -1, "", 1);// 915
			AddComplexComponent( (BaseAddon) this, 1848, -5, 0, 0, 2404, -1, "", 1);// 916
			AddComplexComponent( (BaseAddon) this, 1848, -5, -1, 0, 2404, -1, "", 1);// 917
			AddComplexComponent( (BaseAddon) this, 1848, -5, -2, 0, 2404, -1, "", 1);// 918
			AddComplexComponent( (BaseAddon) this, 1848, -5, -3, 0, 2404, -1, "", 1);// 919
			AddComplexComponent( (BaseAddon) this, 1848, -5, -4, 0, 2404, -1, "", 1);// 920
			AddComplexComponent( (BaseAddon) this, 1848, -5, -5, 0, 2404, -1, "", 1);// 921
			AddComplexComponent( (BaseAddon) this, 1848, -5, -6, 0, 2404, -1, "", 1);// 922
			AddComplexComponent( (BaseAddon) this, 1848, -6, 4, 0, 2404, -1, "", 1);// 923
			AddComplexComponent( (BaseAddon) this, 1848, -6, 3, 0, 2404, -1, "", 1);// 924
			AddComplexComponent( (BaseAddon) this, 1848, -6, 2, 0, 2404, -1, "", 1);// 925
			AddComplexComponent( (BaseAddon) this, 1848, -6, 1, 0, 2404, -1, "", 1);// 926
			AddComplexComponent( (BaseAddon) this, 1848, -6, 0, 0, 2404, -1, "", 1);// 927
			AddComplexComponent( (BaseAddon) this, 1848, -6, -1, 0, 2404, -1, "", 1);// 928
			AddComplexComponent( (BaseAddon) this, 1848, -6, -2, 0, 2404, -1, "", 1);// 929
			AddComplexComponent( (BaseAddon) this, 1848, -6, -3, 0, 2404, -1, "", 1);// 930
			AddComplexComponent( (BaseAddon) this, 1848, -6, -4, 0, 2404, -1, "", 1);// 931
			AddComplexComponent( (BaseAddon) this, 1848, -6, -5, 0, 2404, -1, "", 1);// 932
			AddComplexComponent( (BaseAddon) this, 1848, -6, -6, 0, 2404, -1, "", 1);// 933
			AddComplexComponent( (BaseAddon) this, 1848, -7, 4, 0, 2404, -1, "", 1);// 934
			AddComplexComponent( (BaseAddon) this, 1848, -7, 3, 0, 2404, -1, "", 1);// 935
			AddComplexComponent( (BaseAddon) this, 1848, -7, 2, 0, 2404, -1, "", 1);// 936
			AddComplexComponent( (BaseAddon) this, 1848, -7, 1, 0, 2404, -1, "", 1);// 937
			AddComplexComponent( (BaseAddon) this, 1848, -7, 0, 0, 2404, -1, "", 1);// 938
			AddComplexComponent( (BaseAddon) this, 1848, -7, -1, 0, 2404, -1, "", 1);// 939
			AddComplexComponent( (BaseAddon) this, 1848, -7, -2, 0, 2404, -1, "", 1);// 940
			AddComplexComponent( (BaseAddon) this, 1848, -7, -3, 0, 2404, -1, "", 1);// 941
			AddComplexComponent( (BaseAddon) this, 1848, -7, -4, 0, 2404, -1, "", 1);// 942
			AddComplexComponent( (BaseAddon) this, 1848, -7, -5, 0, 2404, -1, "", 1);// 943
			AddComplexComponent( (BaseAddon) this, 1848, -7, -6, 0, 2404, -1, "", 1);// 944
			AddComplexComponent( (BaseAddon) this, 1848, -3, -7, 0, 2404, -1, "", 1);// 945
			AddComplexComponent( (BaseAddon) this, 1848, -4, -7, 0, 2404, -1, "", 1);// 946
			AddComplexComponent( (BaseAddon) this, 1848, -5, -7, 0, 2404, -1, "", 1);// 947
			AddComplexComponent( (BaseAddon) this, 1848, -6, -7, 0, 2404, -1, "", 1);// 948
			AddComplexComponent( (BaseAddon) this, 1848, -7, -7, 0, 2404, -1, "", 1);// 949

		}

		public KitsCaveHouseThreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KitsCaveHouseThreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KitsCaveHouseThreeAddon();
			}
		}

		[Constructable]
		public KitsCaveHouseThreeAddonDeed()
		{
			Name = "KitsCaveHouseThree";
		}

		public KitsCaveHouseThreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}