
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DeerTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19096, 0, 1, 2}, {40376, 0, 0, 2}, {9007, 0, 0, 54}// 1	2	3	
			, {40385, 0, 1, 34}, {14962, 0, 3, 11}, {40386, 1, 0, 23}// 7	9	54	
			, {40387, 1, 0, 4}, {14934, 1, -2, 1}, {14943, 2, -1, 3}// 55	61	62	
			, {14961, 1, 3, 11}// 63	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DeerTreeAddonDeed();
			}
		}

		[ Constructable ]
		public DeerTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 40955, 0, 1, 22, 0, 0, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 40955, 0, 0, 22, 0, 0, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 40955, 0, 0, 43, 0, 0, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 40837, 0, 2, 5, 33, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2750, -2, 2, 2, 2176, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2808, 3, 2, 2, 2176, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2750, -1, 2, 2, 2176, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2754, 3, 3, 2, 2176, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2750, 0, 2, 2, 2176, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2809, -2, 3, 2, 2176, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2809, -1, 3, 2, 2176, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2809, 2, 3, 2, 2176, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2750, 1, 2, 2, 2176, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2750, 2, 2, 2, 2176, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2809, 0, 3, 2, 2176, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2809, 1, 3, 2, 2176, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2750, -2, -2, 2, 2176, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2757, 3, -3, 2, 2176, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2807, -1, -3, 2, 2176, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2750, 1, -2, 2, 2176, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2750, -1, 0, 2, 2176, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2808, 3, -2, 2, 2176, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2750, -1, -2, 2, 2176, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2750, 2, -1, 2, 2176, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2808, 3, 0, 2, 2176, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2807, 1, -3, 2, 2176, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2808, 3, 1, 2, 2176, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2750, -1, 1, 2, 2176, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2750, 0, -1, 2, 2176, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2750, -2, -1, 2, 2176, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2750, 1, 1, 2, 2176, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2750, 0, 1, 2, 2176, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2750, -1, -1, 2, 2176, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2750, 2, 0, 2, 2176, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2808, 3, -1, 2, 2176, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2750, 0, 0, 2, 2176, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2750, 1, -1, 2, 2176, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2750, 2, 1, 2, 2176, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2750, 0, -2, 2, 2176, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2750, 1, 0, 2, 2176, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2750, -2, 0, 2, 2176, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2807, 2, -3, 2, 2176, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2807, -2, -3, 2, 2176, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2750, 2, -2, 2, 2176, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2750, -2, 1, 2, 2176, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2807, 0, -3, 2, 2176, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 40960, 1, 0, 20, 0, 0, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 40960, 1, 1, 44, 0, 0, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 9003, 1, 1, 9, 376, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 18086, 1, -1, 0, 1173, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 18083, 2, 1, 9, 1194, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 18082, 2, 0, 7, 2123, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 18087, 1, 0, 3, 1196, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2806, -3, 2, 2, 2176, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 2756, -3, 3, 2, 2176, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 2755, -3, -3, 2, 2176, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 2806, -3, 1, 2, 2176, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 2806, -3, -2, 2, 2176, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 2806, -3, -1, 2, 2176, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 2806, -3, 0, 2, 2176, -1, "", 1);// 70

		}

		public DeerTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DeerTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DeerTreeAddon();
			}
		}

		[Constructable]
		public DeerTreeAddonDeed()
		{
			Name = "DeerTree";
		}

		public DeerTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}