
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RockGarden2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6045, 1, 1, 1}, {6049, 0, 2, 1}, {6021, 3, 2, 1}// 1	2	3	
			, {6021, 3, 1, 1}, {6020, 1, 3, 1}, {6020, 2, 3, 1}// 4	5	6	
			, {6020, -1, 3, 1}, {3208, 2, 2, 1}, {3211, -2, 0, 1}// 7	8	9	
			, {3211, 1, 1, 1}, {3231, 3, 1, 1}, {3219, 1, 2, 0}// 10	11	12	
			, {3244, 3, 0, 1}, {3245, 0, 3, 1}, {3204, 3, -1, 1}// 13	14	15	
			, {3204, 1, 3, 2}, {3223, -1, 2, 1}, {3256, 2, 0, 1}// 16	17	18	
			, {3256, 1, -2, 1}, {3256, 1, -1, 5}, {3255, -2, 2, 1}// 19	20	21	
			, {3219, 2, 1, 0}, {6012, 2, 0, 2}, {4973, -1, 2, 1}// 22	23	24	
			, {4970, 2, 2, 0}, {4963, 2, -1, 1}, {6039, 2, 2, 1}// 25	26	27	
			, {6039, 2, 1, 1}, {6039, 2, 0, 1}, {6039, 2, -1, 1}// 28	29	30	
			, {6039, 1, 2, 1}, {6039, 1, 1, 1}, {6039, 1, 0, 1}// 31	32	33	
			, {6039, 1, -1, 1}, {6039, 0, 2, 1}, {6039, 0, 1, 1}// 34	35	36	
			, {6039, 0, 0, 1}, {6039, 0, -1, 1}, {6039, -1, 2, 1}// 37	38	39	
			, {6039, -1, 1, 1}, {6039, -1, 0, 1}, {6039, -1, -1, 1}// 40	41	42	
			, {6006, 1, 0, 1}, {6010, 0, 1, 1}, {6004, 1, 1, 4}// 43	44	45	
			, {6002, -1, 1, 1}, {4967, 1, -1, 3}, {4963, 0, 0, 1}// 46	47	48	
			, {4945, 0, -1, 1}, {4943, -1, 0, 1}// 49	50	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RockGarden2AddonDeed();
			}
		}

		[ Constructable ]
		public RockGarden2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public RockGarden2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RockGarden2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RockGarden2Addon();
			}
		}

		[Constructable]
		public RockGarden2AddonDeed()
		{
			Name = "RockGarden2";
		}

		public RockGarden2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}