
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace BloodyFountain
{
	public class BloodyFountainAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4650, 0, 1, 6}, {4650, 0, 0, 6}, {4650, 0, 0, 9}// 1	2	3	
			, {4650, 1, 0, 6}, {4650, 1, 0, 6}, {4650, 1, 1, 7}// 4	5	6	
			, {4651, 0, 2, 6}, {4651, 2, 1, 6}, {4651, 2, 2, 0}// 7	8	9	
			, {4651, 1, 2, 0}, {4651, -1, 3, 0}, {4651, 2, 0, 0}// 10	11	12	
			, {4651, 1, -1, 6}, {4651, 2, 0, 6}, {4651, -1, 1, 6}// 13	14	15	
			, {7597, 1, 1, 7}, {7601, 0, 1, 6}, {7588, 2, 0, 6}// 16	17	18	
			, {7408, 1, 2, 6}, {7401, -1, 2, 6}, {4651, 2, -1, 0}// 19	20	21	
			, {4651, 0, -2, 0}, {4651, -2, -1, 0}, {4651, 0, 2, 6}// 22	23	24	
			, {4651, -1, -1, 6}, {4651, 1, 3, 0}, {4651, 2, 0, 0}// 25	26	27	
			, {4651, 0, 2, 6}, {4651, 1, 1, 6}, {4651, 2, 0, 6}// 28	29	30	
			, {4651, 3, 0, 0}, {4651, -3, 2, 0}// 31	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BloodyFountainAddonDeed();
			}
		}

		[ Constructable ]
		public BloodyFountainAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5937, -1, 2, 0, 1096, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 5938, 0, 2, 0, 1096, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 5939, 1, 2, 0, 1096, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 5940, 2, 2, 0, 1096, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 5941, 2, 1, 0, 1096, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 5942, 2, 0, 0, 1096, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 5943, 2, -1, 0, 1096, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 5944, 1, -1, 0, 1096, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 5945, 1, 0, 0, 1096, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 5946, 1, 1, 0, 1096, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 5947, 0, 1, 0, 1096, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 5948, -1, 1, 0, 1096, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 5949, -1, 0, 0, 1096, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 5950, 0, 0, 0, 1096, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 5951, 0, -1, 0, 1096, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 5953, -1, -1, 0, 1096, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2339, 0, 0, 9, 32, -1, "", 1);// 58

		}

		public BloodyFountainAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BloodyFountainAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BloodyFountainAddon();
			}
		}

		[Constructable]
		public BloodyFountainAddonDeed()
		{
			Name = "BloodyFountain";
		}

		public BloodyFountainAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}