
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace ElectricChair
{
	public class ElectricChairAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4237, 0, 2, 10}, {2860, 4, 0, 2}, {2860, 4, 1, 2}// 19	20	21	
			, {2860, 4, 2, 2}, {2860, 4, 3, 2}, {2860, 4, -1, 2}// 22	23	24	
			, {2860, 5, -1, 2}, {2860, 5, 0, 2}, {2860, 5, 1, 2}// 25	26	27	
			, {2860, 5, 2, 2}, {2860, 5, 3, 2}, {2081, -6, -3, 2}// 28	29	32	
			, {2081, -6, -2, 2}, {2081, -6, -1, 2}, {2081, -6, 0, 2}// 33	34	35	
			, {2081, -6, 1, 2}, {2081, -6, 2, 2}, {2081, -6, 3, 2}// 36	37	38	
			, {2081, -6, 4, 2}, {2081, -6, 5, 2}, {2083, -5, 5, 2}// 39	40	41	
			, {2083, -4, 5, 2}, {2083, -3, 5, 2}, {2083, -2, 5, 2}// 42	43	44	
			, {2083, -1, 5, 2}, {2083, 0, 5, 2}, {2083, 1, 5, 2}// 45	46	47	
			, {2083, 2, 5, 2}, {2083, 3, 5, 2}, {2083, 4, 5, 2}// 48	49	50	
			, {2083, 5, 5, 2}, {2083, 6, 5, 2}, {2083, -5, -4, 2}// 51	52	53	
			, {2083, -4, -4, 2}, {2083, -3, -4, 2}, {2083, -2, -4, 2}// 54	55	56	
			, {2083, -1, -4, 2}, {2083, 0, -4, 2}, {2083, 1, -4, 2}// 57	58	59	
			, {2083, 2, -4, 2}, {2083, 3, -4, 2}, {2083, 4, -4, 2}// 60	61	62	
			, {2083, 5, -4, 2}, {2083, 6, -4, 2}, {2083, 7, 5, 2}// 63	64	65	
			, {2083, 7, -4, 2}, {2081, 7, -3, 2}, {2081, 7, -2, 2}// 66	67	68	
			, {2081, 7, -1, 2}, {2081, 7, 5, 2}, {2081, 7, 4, 2}// 69	70	71	
			, {2081, 7, 3, 2}// 72	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElectricChairAddonDeed();
			}
		}

		[ Constructable ]
		public ElectricChairAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2592, -3, 1, 10, 1, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2971, -2, 1, 11, 1754, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2330, -2, 1, 21, 1083, -1, "Bank Hive", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1006, -2, 2, 0, 1096, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1006, -1, 2, 0, 1096, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1006, 0, 2, 0, 1096, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1006, 0, 0, 0, 1096, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1006, -2, 1, 0, 1096, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1006, -2, 0, 0, 1096, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1006, -1, 0, 0, 1096, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1006, -1, 1, 0, 1096, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1006, 0, 1, 0, 1096, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1006, -3, 1, 0, 1096, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1006, -3, 2, 0, 1096, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1006, -3, 0, 0, 1096, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1008, 1, 1, 0, 1096, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1008, 1, 2, 0, 1096, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1008, 1, 0, 0, 1096, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 14662, -3, 1, 6, 0, 1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 11747, -2, 1, 6, 1083, -1, "", 1);// 31

		}

		public ElectricChairAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElectricChairAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElectricChairAddon();
			}
		}

		[Constructable]
		public ElectricChairAddonDeed()
		{
			Name = "ElectricChair";
		}

		public ElectricChairAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}