
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace FelHalloweenTree
{
	public class FelHalloweenTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7869, 1, 1, 0}, {7869, 1, -1, 0}, {3178, 1, 1, 0}// 13	14	15	
			, {3178, 2, 0, 0}, {3178, 2, 1, 0}, {3893, 1, 1, 0}// 16	17	18	
			, {3893, 2, 0, 0}, {3893, 2, -1, 0}, {3893, 2, 1, 0}// 19	20	21	
			, {3893, 0, 0, 0}, {3893, -1, -1, 0}, {3811, 2, 0, 0}// 22	23	24	
			, {3811, 2, 1, 0}// 25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FelHalloweenTreeAddonDeed();
			}
		}

		[ Constructable ]
		public FelHalloweenTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3323, 1, 0, 0, 1083, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6884, 1, 0, 20, 1154, -1, "Mythic skull", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6884, 1, 0, 20, 1154, -1, "Mythic skull", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6884, 1, -1, 6, 1154, -1, "Mythic skull", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6884, 1, 1, 12, 1154, -1, "Mythic skull", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6884, -1, -1, 3, 1154, -1, "Mythic skull", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6884, 1, 0, 11, 1154, -1, "Mythic skull", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6884, 1, 0, 26, 1154, -1, "Mythic skull", 1);// 8
			AddComplexComponent( (BaseAddon) this, 9014, 1, 0, 20, 2170, 0, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 9014, 0, 0, 0, 2170, 0, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 9014, 1, 1, 0, 2170, 0, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 9014, 2, 0, 0, 2170, 0, "", 1);// 12

		}

		public FelHalloweenTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FelHalloweenTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FelHalloweenTreeAddon();
			}
		}

		[Constructable]
		public FelHalloweenTreeAddonDeed()
		{
			Name = "FelHalloweenTree";
		}

		public FelHalloweenTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}