
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace HalloweenGazeebo
{
	public class HalloweenGazeeboAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2860, -2, 1, 5}, {2860, -2, 0, 5}, {2860, -2, -1, 5}// 105	106	107	
			, {2860, 2, 1, 5}, {2860, 2, 0, 5}, {2860, 2, -1, 5}// 108	109	110	
			, {2861, -1, -2, 5}, {2861, 0, -2, 5}, {2861, 1, -2, 5}// 111	112	113	
			, {2861, -1, 2, 5}, {2861, 0, 2, 5}, {2861, 1, 2, 5}// 114	115	116	
			, {3311, 3, 2, 2}, {3311, -2, -2, 5}, {3311, -3, 1, 2}// 117	121	125	
			, {3307, 2, -2, 5}, {3307, 2, 3, 2}, {3307, -2, 3, 5}// 130	134	138	
			, {3178, 3, 4, 0}, {3178, 3, 3, 0}, {3178, 3, 3, 0}// 141	142	143	
			, {3178, 3, 3, 0}, {3178, 3, -3, 0}, {3178, 4, -2, 5}// 144	145	146	
			, {3178, -3, 4, 0}, {3178, -2, -1, 45}, {3178, 2, -1, 45}// 147	161	162	
			, {3178, 2, 1, 45}, {3178, -1, 2, 45}// 163	164	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HalloweenGazeeboAddonDeed();
			}
		}

		[ Constructable ]
		public HalloweenGazeeboAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1848, -2, 1, 0, 1083, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1848, -2, 0, 0, 1083, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1848, -2, -2, 0, 1083, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1848, -2, -1, 0, 1083, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1848, -1, -2, 0, 1083, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 0, 1083, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1848, 1, -2, 0, 1083, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1848, 2, -2, 0, 1083, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1848, 2, -1, 0, 1083, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1848, 2, 0, 0, 1083, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1848, 2, 1, 0, 1083, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1848, 2, 2, 0, 1083, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1848, 1, 2, 0, 1083, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1848, -1, 2, 0, 1083, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1848, -2, 2, 0, 1083, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 0, 1083, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1848, -1, 1, 0, 1083, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1848, -1, -1, 0, 1083, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1848, -1, 0, 0, 1083, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 0, 1083, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1848, 1, -1, 0, 1083, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1848, 1, 0, 0, 1083, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1848, 0, 1, 0, 1083, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1848, 1, 1, 0, 1083, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1848, 0, 0, 0, 1083, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1849, -2, 3, 0, 1083, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1849, -1, 3, 0, 1083, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1849, 0, 3, 0, 1083, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1849, 1, 3, 0, 1083, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1849, 2, 3, 0, 1083, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1850, 3, -2, 0, 1083, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1850, 3, -1, 0, 1083, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1850, 3, 0, 0, 1083, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1850, 3, 1, 0, 1083, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1850, 3, 2, 0, 1083, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1851, -2, -3, 0, 1083, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1851, -1, -3, 0, 1083, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1851, 0, -3, 0, 1083, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1851, 1, -3, 0, 1083, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1851, 2, -3, 0, 1083, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1852, -3, -2, 0, 1083, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1852, -3, -1, 0, 1083, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1852, -3, 0, 0, 1083, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1852, -3, 1, 0, 1083, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1852, -3, 2, 0, 1083, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1595, -2, -2, 45, 2170, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1595, -2, -2, 45, 2170, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1595, -2, -1, 45, 2170, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1595, -2, 0, 45, 2170, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1595, -2, 1, 45, 2170, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1595, -2, 2, 45, 2170, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1595, -1, -2, 45, 2170, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1595, -1, -1, 45, 2170, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1595, -1, 0, 45, 2170, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1595, -1, 1, 45, 2170, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1595, -1, 2, 45, 2170, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1595, 0, -2, 45, 2170, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1595, 0, -1, 45, 2170, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1595, 0, 0, 45, 2170, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1595, 0, 1, 45, 2170, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1595, 0, 2, 45, 2170, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1595, 1, -2, 45, 2170, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1595, 1, -1, 45, 2170, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1595, 1, 0, 45, 2170, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1595, 1, 1, 45, 2170, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1595, 1, 2, 45, 2170, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1595, 2, -2, 45, 2170, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1595, 2, -1, 45, 2170, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1595, 2, 0, 45, 2170, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1595, 2, 1, 45, 2170, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1595, 2, 2, 45, 2170, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 298, 2, 2, 6, 1083, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 298, 2, -3, 6, 1083, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 298, -3, 2, 6, 1083, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 298, -3, -3, 5, 1083, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 298, 2, -3, 26, 1083, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 298, 2, 2, 26, 1083, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 298, -3, 2, 26, 1083, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 298, -3, -3, 25, 1083, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 321, 2, 2, 45, 1083, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 322, -2, 2, 45, 1083, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 322, -1, 2, 45, 1083, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 322, 0, 2, 45, 1083, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 322, 1, 2, 45, 1083, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 322, -2, -3, 45, 1083, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 322, -1, -3, 45, 1083, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 322, 0, -3, 45, 1083, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 322, 1, -3, 45, 1083, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 322, 2, -3, 45, 1083, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 323, 2, -2, 45, 1083, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 323, 2, -1, 45, 1083, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 323, 2, 0, 45, 1083, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 323, 2, 1, 45, 1083, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 323, -3, -2, 45, 1083, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 323, -3, -1, 45, 1083, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 323, -3, 0, 45, 1083, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 323, -3, 1, 45, 1083, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 323, -3, 2, 45, 1083, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 324, -3, -3, 45, 1083, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 3237, 3, 3, 0, 1083, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 3237, 3, -3, 0, 1083, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 3237, -3, 3, 0, 1083, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 3237, -3, -3, 0, 1083, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 10749, 0, 0, 5, 0, 1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 3196, 3, 2, 16, 1799, -1, "Rose", 1);// 118
			AddComplexComponent( (BaseAddon) this, 3195, 3, 3, 25, 1799, -1, "Rose", 1);// 119
			AddComplexComponent( (BaseAddon) this, 3195, 3, 3, 13, 1799, -1, "Rose", 1);// 120
			AddComplexComponent( (BaseAddon) this, 3196, -2, -2, 19, 1799, -1, "Rose", 1);// 122
			AddComplexComponent( (BaseAddon) this, 3195, -2, -1, 28, 1799, -1, "Rose", 1);// 123
			AddComplexComponent( (BaseAddon) this, 3195, -2, -1, 16, 1799, -1, "Rose", 1);// 124
			AddComplexComponent( (BaseAddon) this, 3196, -3, 1, 16, 1799, -1, "Rose", 1);// 126
			AddComplexComponent( (BaseAddon) this, 3195, -3, 2, 25, 1799, -1, "Rose", 1);// 127
			AddComplexComponent( (BaseAddon) this, 3195, -3, 2, 13, 1799, -1, "Rose", 1);// 128
			AddComplexComponent( (BaseAddon) this, 3196, 2, -2, 19, 1799, -1, "Rose", 1);// 129
			AddComplexComponent( (BaseAddon) this, 3195, 2, -2, 12, 1799, -1, "Rose", 1);// 131
			AddComplexComponent( (BaseAddon) this, 3195, 2, -2, 22, 1799, -1, "Rose", 1);// 132
			AddComplexComponent( (BaseAddon) this, 3196, 2, 3, 16, 1799, -1, "Rose", 1);// 133
			AddComplexComponent( (BaseAddon) this, 3195, 2, 3, 9, 1799, -1, "Rose", 1);// 135
			AddComplexComponent( (BaseAddon) this, 3195, 2, 3, 19, 1799, -1, "Rose", 1);// 136
			AddComplexComponent( (BaseAddon) this, 3196, -2, 3, 19, 1799, -1, "Rose", 1);// 137
			AddComplexComponent( (BaseAddon) this, 3195, -2, 3, 12, 1799, -1, "Rose", 1);// 139
			AddComplexComponent( (BaseAddon) this, 3195, -2, 3, 22, 1799, -1, "Rose", 1);// 140
			AddComplexComponent( (BaseAddon) this, 9417, 3, -2, 2, 0, 1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 9417, 3, 2, 2, 0, 1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 9417, -2, 3, 2, 0, 1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 9417, 2, 3, 2, 0, 1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 9417, -2, -3, 5, 0, 1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 9417, -3, -2, 5, 0, 1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 9417, -3, 1, 5, 0, 1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 9417, 2, -2, 20, 0, 1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 3237, -2, -2, 45, 1083, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 3237, 2, -2, 45, 1083, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 3237, 2, 2, 45, 1083, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 3237, -2, 2, 45, 1083, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 3237, 0, 0, 45, 1083, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 9014, -1, 3, 2, 1360, 0, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 9014, 0, 0, 5, 1360, 0, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 9014, 3, -1, 2, 1360, 0, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 9014, 0, -1, 5, 1360, 0, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 9014, 0, -2, 6, 1360, 0, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 9014, -3, 0, 2, 1360, 0, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 9014, 0, 2, 45, 43, 0, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 9014, 1, -1, 45, 1360, 0, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 9014, 2, 2, 48, 1360, 0, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 9014, 3, 0, 2, 44, 0, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 9014, 0, 3, 2, 1360, 0, "", 1);// 175

		}

		public HalloweenGazeeboAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HalloweenGazeeboAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HalloweenGazeeboAddon();
			}
		}

		[Constructable]
		public HalloweenGazeeboAddonDeed()
		{
			Name = "HalloweenGazeebo";
		}

		public HalloweenGazeeboAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}