
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace LeafPile
{
	public class LeafPileAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LeafPileAddonDeed();
			}
		}

		[ Constructable ]
		public LeafPileAddon()
		{



			AddComplexComponent( (BaseAddon) this, 6950, 0, 1, 0, 1360, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6949, 0, 0, 0, 1360, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6948, 1, 0, 0, 1360, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6947, 1, 1, 0, 1360, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6946, 1, 1, 0, 1360, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6946, -1, 1, 0, 1360, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6946, -1, 0, 0, 1360, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6946, 0, -1, 0, 1360, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6946, 1, -1, 0, 1360, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6946, 2, 0, 0, 1360, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6946, 2, -1, 0, 1360, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6946, 2, 1, 0, 1360, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6946, 1, 2, 0, 1360, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6946, 0, 2, 0, 1360, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6946, 2, 2, 0, 1360, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6944, -1, 2, 0, 1360, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6944, -1, -1, 0, 1360, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6943, -1, 1, 0, 44, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6943, 1, 1, 0, 44, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6943, 2, 0, 0, 44, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6943, 2, -1, 0, 44, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6943, 0, -1, 0, 44, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6943, 0, 0, 0, 44, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6943, 0, 1, 0, 44, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6943, 1, 0, 0, 44, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6943, 0, 2, 0, 44, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6943, -1, 2, 0, 44, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6943, 1, 2, 0, 44, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6943, 1, 0, 0, 44, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3719, 0, 2, 0, 0, -1, "A Rake", 1);// 30

		}

		public LeafPileAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LeafPileAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LeafPileAddon();
			}
		}

		[Constructable]
		public LeafPileAddonDeed()
		{
			Name = "LeafPile";
		}

		public LeafPileAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}