
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace HalloweenBloodBath
{
	public class HalloweenBloodBathAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7400, 2, 4, 1}, {7401, 2, 1, 16}, {7599, -1, 4, 1}// 7	11	15	
			, {4310, 0, -1, 1}, {7408, 0, 0, 1}, {7394, 0, 1, 1}// 17	21	22	
			, {7406, 0, 4, 1}, {7407, 2, -2, 2}, {7398, 2, -1, 0}// 27	29	30	
			, {4310, 2, -1, 0}, {5696, 2, 0, 0}, {7401, 2, 0, 16}// 31	33	34	
			, {7374, 2, 1, 0}, {5696, 2, 1, 0}, {7368, 2, -1, 0}// 35	37	38	
			, {1301, 1, -2, 5}, {6941, 2, -4, 0}, {6941, 2, -3, 2}// 44	48	51	
			, {7601, 1, 3, 1}, {4310, 1, 3, 1}, {7408, 0, -4, 16}// 59	60	63	
			, {7584, 0, -3, 15}, {1301, 0, -2, 5}, {7402, 0, -1, 0}// 69	71	73	
			, {7405, -1, 3, 1}, {7588, -1, 3, 1}, {7405, -1, 1, 1}// 75	76	80	
			, {7587, -1, 1, 1}, {7398, -1, -1, 0}, {7397, -1, -1, 0}// 81	85	86	
			, {1301, -1, -2, 5}, {7405, -1, -4, 16}, {7390, 0, 5, 1}// 87	92	109	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HalloweenBloodBathAddonDeed();
			}
		}

		[ Constructable ]
		public HalloweenBloodBathAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6051, -3, 4, 0, 33, -1, "blood", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6051, -3, 3, 0, 33, -1, "blood", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6054, -3, 2, 0, 33, -1, "blood", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6056, -3, 5, 0, 33, -1, "blood", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6045, 3, 4, 0, 33, -1, "blood", 1);// 5
			AddComplexComponent( (BaseAddon) this, 13422, 2, 4, 0, 33, -1, "blood", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6053, 3, 2, 0, 33, -1, "blood", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6046, 3, 3, 0, 33, -1, "blood", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6057, 2, 2, 0, 33, -1, "blood", 1);// 10
			AddComplexComponent( (BaseAddon) this, 13422, 2, 3, 0, 33, -1, "blood", 1);// 12
			AddComplexComponent( (BaseAddon) this, 641, 0, -5, 0, 962, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 641, 1, -5, 0, 962, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13422, 0, -4, 12, 33, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 13443, 0, 0, 0, 33, -1, "blood", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13443, 0, -1, 0, 33, -1, "blood", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13422, 0, 1, 0, 33, -1, "blood", 1);// 20
			AddComplexComponent( (BaseAddon) this, 632, 0, 2, 0, 942, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 13422, 0, 2, 0, 33, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13422, 0, 3, 0, 33, -1, "blood", 1);// 25
			AddComplexComponent( (BaseAddon) this, 13422, 0, 4, 0, 33, -1, "blood", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1874, 2, -2, 0, 942, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7383, 2, 0, 0, 0, -1, "blood", 1);// 32
			AddComplexComponent( (BaseAddon) this, 6046, 2, 1, 0, 33, -1, "blood", 1);// 36
			AddComplexComponent( (BaseAddon) this, 631, 1, -3, 0, 942, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13443, 1, -3, 0, 33, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 642, 1, -3, 0, 962, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 635, 1, -2, 0, 942, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 636, 1, -2, 0, 942, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 636, 1, -1, 0, 942, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 13443, 1, -1, 0, 33, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 642, 1, -4, 0, 942, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 4313, 2, -3, 0, 962, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 4306, 2, -4, 0, 962, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 13443, 1, 0, 0, 33, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 633, 1, 1, 0, 962, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 13422, 1, 1, 0, 33, -1, "blood", 1);// 54
			AddComplexComponent( (BaseAddon) this, 635, 1, 2, 0, 942, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 634, 1, 2, 0, 962, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 13422, 1, 2, 0, 33, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 13422, 1, 3, 0, 33, -1, "blood", 1);// 58
			AddComplexComponent( (BaseAddon) this, 13422, 1, 4, 0, 33, -1, "blood", 1);// 61
			AddComplexComponent( (BaseAddon) this, 633, 1, 0, 0, 942, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 6041, 0, -4, 0, 33, -1, "blood", 1);// 64
			AddComplexComponent( (BaseAddon) this, 631, 0, -3, 0, 942, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 13579, 0, -3, 10, 33, -1, "blood", 1);// 66
			AddComplexComponent( (BaseAddon) this, 13443, 0, -3, 0, 33, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 13422, 0, -4, 15, 33, -1, "blood", 1);// 68
			AddComplexComponent( (BaseAddon) this, 635, 0, -2, 0, 942, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 7408, 0, -2, 5, 33, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 13422, -1, 4, 0, 33, -1, "blood", 1);// 74
			AddComplexComponent( (BaseAddon) this, 13422, -1, 3, 0, 33, -1, "blood", 1);// 77
			AddComplexComponent( (BaseAddon) this, 13422, -1, 2, 0, 33, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 631, -1, 2, 0, 942, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 13422, -1, 1, 0, 33, -1, "blood", 1);// 82
			AddComplexComponent( (BaseAddon) this, 13443, -1, 0, 0, 33, -1, "blood", 1);// 83
			AddComplexComponent( (BaseAddon) this, 13443, -1, -1, 0, 33, -1, "blood", 1);// 84
			AddComplexComponent( (BaseAddon) this, 632, -1, -2, 0, 942, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 13443, -1, -3, 0, 33, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 13579, -1, -3, 10, 33, -1, "blood", 1);// 90
			AddComplexComponent( (BaseAddon) this, 631, -1, -3, 0, 942, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 13422, -1, -4, 15, 33, -1, "blood", 1);// 93
			AddComplexComponent( (BaseAddon) this, 13422, -1, -4, 0, 33, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 641, -1, -5, 0, 962, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 13422, -2, 4, 0, 33, -1, "blood", 1);// 96
			AddComplexComponent( (BaseAddon) this, 13422, -2, 3, 0, 33, -1, "blood", 1);// 97
			AddComplexComponent( (BaseAddon) this, 6060, -2, 2, 0, 33, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 636, -2, 2, 0, 942, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 633, -2, 1, 0, 962, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 633, -2, 0, 0, 962, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 634, -2, -1, 0, 942, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1876, -2, -2, 0, 942, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 642, -2, -3, 0, 942, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 642, -2, -4, 0, 962, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 6055, 3, 5, 0, 33, -1, "blood", 1);// 106
			AddComplexComponent( (BaseAddon) this, 6058, 2, 5, 0, 33, -1, "blood", 1);// 107
			AddComplexComponent( (BaseAddon) this, 13422, 1, 5, 0, 33, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 13422, 0, 5, 0, 33, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 13422, -1, 5, 0, 33, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 6059, -2, 5, 0, 33, -1, "blood", 1);// 112

		}

		public HalloweenBloodBathAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HalloweenBloodBathAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HalloweenBloodBathAddon();
			}
		}

		[Constructable]
		public HalloweenBloodBathAddonDeed()
		{
			Name = "HalloweenBloodBath";
		}

		public HalloweenBloodBathAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}