
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace HalloweenSkullDaemonPole
{
	public class HalloweenSkullDaemonPoleAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {8708, 1, 1, 40}, {8700, 1, 1, 0}, {6873, 1, 0, 0}// 7	8	9	
			, {6873, 0, 1, 0}, {6875, -1, 1, 0}, {6875, -1, 0, 0}// 10	11	12	
			, {6875, -1, -1, 0}, {6875, 0, -1, 0}, {6875, 1, -1, 0}// 13	14	15	
			, {6874, -2, 1, 0}, {6874, -2, -1, 0}, {8708, 1, 1, 21}// 16	17	18	
			, {6877, 1, -2, 0}, {6877, 0, -2, 0}, {4650, 0, 2, 0}// 19	20	21	
			, {4652, 2, 0, 0}, {4654, 2, 0, 0}, {4652, 0, -2, 0}// 22	23	24	
			, {4653, 2, 1, 0}, {4654, -2, 0, 0}// 25	26	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HalloweenSkullDaemonPoleAddonDeed();
			}
		}

		[ Constructable ]
		public HalloweenSkullDaemonPoleAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 8783, 0, 1, 32, 33, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 12268, 0, 0, 0, 1, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 8783, 0, 1, 48, 33, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 8782, 1, 0, 41, 33, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 8782, 1, 0, 22, 33, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7967, 0, 0, 41, 33, -1, "", 1);// 6

		}

		public HalloweenSkullDaemonPoleAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HalloweenSkullDaemonPoleAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HalloweenSkullDaemonPoleAddon();
			}
		}

		[Constructable]
		public HalloweenSkullDaemonPoleAddonDeed()
		{
			Name = "HalloweenSkullDaemonPole";
		}

		public HalloweenSkullDaemonPoleAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}