
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace TreeOfLifeRug
{
	public class TreeOfLifeRugAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {40514, 1, 1, 0}, {40507, 0, 1, 0}, {40513, 1, 0, 0}// 1	2	3	
			, {40512, 1, -1, 0}, {40510, -1, -1, 0}, {40511, 0, -1, 0}// 4	5	6	
			, {40508, -1, 1, 0}, {40509, -1, 0, 0}, {40506, 0, 0, 0}// 7	8	9	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TreeOfLifeRugAddonDeed();
			}
		}

		[ Constructable ]
		public TreeOfLifeRugAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public TreeOfLifeRugAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TreeOfLifeRugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TreeOfLifeRugAddon();
			}
		}

		[Constructable]
		public TreeOfLifeRugAddonDeed()
		{
			Name = "TreeOfLifeRug";
		}

		public TreeOfLifeRugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}