
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GameTableAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4006, 0, 0, 4}, {3612, 1, 2, 10}, {3612, 1, -1, 4}// 12	24	25	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GameTableAddonDeed();
			}
		}

		[ Constructable ]
		public GameTableAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1183, 0, -1, 4, 1193, -1, "gaming", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1183, 0, 0, 4, 1193, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1183, 0, 1, 4, 1193, -1, "gaming", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2819, 0, 1, 0, 1193, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2821, 0, -1, 0, 1193, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2820, 0, 0, 0, 1193, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1114, -1, 0, 0, 1153, -1, "gaming", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1115, 0, -2, 0, 1153, -1, "gaming", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1115, 0, 2, 0, 1153, -1, "gaming", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1116, -1, -1, 0, 1153, -1, "gaming", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1116, -1, 1, 0, 1153, -1, "gaming", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1183, 1, -1, 4, 1193, -1, "gaming", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1183, 1, 0, 4, 1193, -1, "gaming", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1183, 1, 1, 4, 1193, -1, "gaming", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2819, 1, 1, 0, 1193, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2820, 1, 0, 0, 1193, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2821, 1, -1, 0, 1193, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1114, 2, 0, 0, 1153, -1, "gaming", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1115, 1, 2, 0, 1153, -1, "gaming", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1115, 1, -2, 0, 1153, -1, "gaming", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1116, 2, -1, 0, 1153, -1, "gaming", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1116, 2, 1, 0, 1153, -1, "gaming", 1);// 23

		}

		public GameTableAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GameTableAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GameTableAddon();
			}
		}

		[Constructable]
		public GameTableAddonDeed()
		{
			Name = "GameTable";
		}

		public GameTableAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}