
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriFireplaceGrayAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7134, 0, 0, 1}, {7134, -1, 0, 2}, {7134, 0, 0, 2}// 2	6	9	
			, {7134, -1, 0, 0}, {19612, 0, 1, 23}, {19613, 1, 1, 23}// 10	12	15	
			, {3235, 3, 0, 21}// 17	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriFireplaceGrayAddonDeed();
			}
		}

		[ Constructable ]
		public CheriFireplaceGrayAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 19467, -2, 0, 21, 2153, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2238, -1, 1, 1, 1096, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2919, -1, 1, 22, 1096, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2238, 0, 1, 1, 1096, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2919, 0, 1, 22, 1096, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3555, -1, 0, 5, 0, 1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3555, 0, 0, 5, 0, 1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2919, 1, 1, 22, 1096, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2919, 2, 1, 22, 1096, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2238, 1, 1, 1, 1096, -1, "", 1);// 16

		}

		public CheriFireplaceGrayAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriFireplaceGrayAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriFireplaceGrayAddon();
			}
		}

		[Constructable]
		public CheriFireplaceGrayAddonDeed()
		{
			Name = "CheriFireplaceGray";
		}

		public CheriFireplaceGrayAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}