
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class cheriWhiteXmasTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7186, -5, -6, 2}, {3289, 1, 1, 5}, {3289, 2, 0, 6}// 1	3	4	
			, {933, 1, 0, 0}// 14	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new cheriWhiteXmasTreeAddonDeed();
			}
		}

		[ Constructable ]
		public cheriWhiteXmasTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3289, 0, 2, 7, 2043, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3289, 3, -1, 7, 2043, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3289, 1, 2, 22, 2043, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3289, 2, 0, 7, 2043, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3289, 3, 0, 23, 2043, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3289, 2, 1, 23, 2043, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3289, 1, 1, 7, 2043, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3289, 2, 2, 45, 2043, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3289, 3, 1, 45, 2043, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3289, 2, 1, 54, 2043, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 9010, 2, 4, 29, 37, 0, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 9010, 1, 2, 0, 32, 0, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 9010, 4, 1, 12, 37, 0, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 9010, 4, 0, 11, 32, 0, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 9010, 3, -1, 2, 0, 0, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 9010, 5, -1, 4, 32, 0, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 9010, 3, 3, 20, 37, 0, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 9010, 3, 2, 19, 32, 0, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 19, 37, 0, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 3, 37, 0, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 9010, 4, 1, 28, 32, 0, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 9010, 4, 0, 28, 32, 0, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 9010, 4, -1, 12, 32, 0, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 9010, 5, 1, 55, 32, 0, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 9010, 5, 2, 55, 37, 0, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 9010, 5, 3, 56, 32, 0, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 9010, 5, 4, 57, 37, 0, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 9010, 5, 5, 60, 37, 0, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 9010, 5, 6, 61, 37, 0, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 9010, 1, 3, 2, 32, 0, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 9010, 2, 3, 42, 37, 0, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 9010, 3, 3, 52, 37, 0, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 9010, 3, 2, 49, 32, 0, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 48, 37, 0, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 9010, 4, 1, 57, 32, 0, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 9010, 2, 2, 52, 32, 0, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 9010, 3, 2, 61, 37, 0, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 59, 37, 0, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 9010, 3, 2, 71, 37, 0, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 69, 37, 0, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3972, 2, 4, 40, 1367, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 3972, 2, 3, 33, 1367, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3972, 4, -1, 24, 1367, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 3972, 2, 1, 23, 1367, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3972, 2, 2, 28, 1367, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 3972, 3, 1, 28, 1367, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 6256, 2, 4, 35, 37, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 7186, 2, 2, 25, 1266, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 6256, 3, 2, 27, 37, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 3972, 3, 0, 22, 1367, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 7186, 4, 1, 30, 1266, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3972, 4, 0, 28, 1367, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 6256, 4, -1, 19, 37, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 3972, 2, 4, 51, 1367, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3972, 2, 3, 44, 1367, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3972, 2, 2, 39, 1367, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 43, 1367, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3972, 4, 2, 49, 1367, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3972, 5, 2, 55, 1367, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 3972, 6, 2, 61, 1367, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 7186, 2, 4, 48, 1266, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6256, 3, 4, 49, 37, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 7186, 3, 2, 40, 1266, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 6256, 3, 1, 32, 37, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 7186, 4, 0, 36, 1266, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 3972, 2, 3, 55, 1367, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 3972, 2, 2, 48, 1367, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 53, 1367, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 3972, 4, 1, 54, 1367, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 3972, 4, 0, 49, 1367, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 3972, 3, 1, 48, 1367, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 7186, 3, 4, 63, 1266, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 6256, 4, 4, 65, 37, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 6256, 4, 1, 50, 37, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 3972, 2, 2, 60, 1367, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 64, 1367, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 3972, 3, 1, 59, 1367, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 3972, 4, 1, 65, 1367, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 7186, 5, 5, 90, 1266, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 6256, 3, 2, 59, 37, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 7186, 5, 2, 74, 1266, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 3972, 2, 2, 69, 1367, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 74, 1367, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 3972, 3, 1, 68, 1367, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 6256, 5, 6, 103, 37, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 7186, 3, 2, 71, 1266, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 6256, 3, 1, 63, 37, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 84, 1367, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 3972, 3, 1, 78, 1367, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 7186, 2, 2, 76, 1266, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 6256, 3, 2, 78, 37, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 7186, 3, 1, 46, 1266, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 7186, 3, 1, 75, 1266, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 9010, 3, 2, 79, 37, 0, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 6256, 3, 2, 88, 37, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 3972, 3, 2, 92, 1367, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 7186, 3, 2, 95, 1266, -1, "", 1);// 101

		}

		public cheriWhiteXmasTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class cheriWhiteXmasTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new cheriWhiteXmasTreeAddon();
			}
		}

		[Constructable]
		public cheriWhiteXmasTreeAddonDeed()
		{
			Name = "cheriWhiteXmasTree";
		}

		public cheriWhiteXmasTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}