
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriCoffeCounter1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2453, 1, 1, 8}, {2455, 1, 1, 8}, {4329, 0, 0, 6}// 12	13	16	
			, {5644, 1, 0, 7}// 17	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriCoffeCounter1AddonDeed();
			}
		}

		[ Constructable ]
		public CheriCoffeCounter1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4497, 1, 0, 0, 1061, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1978, 1, 1, 0, 1117, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1978, 0, 1, 0, 1117, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1978, 0, 0, 0, 1095, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1978, 0, 0, 3, 1117, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1978, 0, 1, 3, 1117, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1978, 1, 1, 3, 1117, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 5354, 0, 1, 8, 2043, -1, "Coffee Maker", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4173, 0, 1, 7, 2043, -1, "Coffee Maker", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7608, 0, 1, 13, 2043, -1, "Coffee Maker", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4086, 0, 1, 8, 2199, -1, "coffee pot", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4102, 0, 0, 9, 0, -1, "suger", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2518, 0, 0, 12, 0, -1, "Cream", 1);// 15

		}

		public CheriCoffeCounter1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriCoffeCounter1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriCoffeCounter1Addon();
			}
		}

		[Constructable]
		public CheriCoffeCounter1AddonDeed()
		{
			Name = "CheriCoffeCounter1";
		}

		public CheriCoffeCounter1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}