
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriPinkLamp3Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6373, 1, 1, 11}, {6373, 1, 1, 15}, {6373, 1, 1, 20}// 6	7	8	
			, {6373, 0, 0, 16}// 9	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriPinkLamp3AddonDeed();
			}
		}

		[ Constructable ]
		public CheriPinkLamp3Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2852, 0, 0, 0, 0, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3184, 0, 0, 20, 1995, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3185, 1, 1, 11, 1995, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3195, 0, 0, 9, 1995, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3196, 1, 1, 18, 1995, -1, "", 1);// 5

		}

		public CheriPinkLamp3Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriPinkLamp3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriPinkLamp3Addon();
			}
		}

		[Constructable]
		public CheriPinkLamp3AddonDeed()
		{
			Name = "CheriPinkLamp3";
		}

		public CheriPinkLamp3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}