
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriPointsettaGarlandNSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18322, 0, -2, 0}, {18322, 0, 1, 2}, {15292, 0, -1, 11}// 1	2	7	
			, {15292, 0, 1, 12}// 8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriPointsettaGarlandNSAddonDeed();
			}
		}

		[ Constructable ]
		public CheriPointsettaGarlandNSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10299, 0, 1, 12, 2175, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 10299, 0, -2, 11, 2175, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 10299, 0, 1, 21, 2175, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 10299, 0, -2, 20, 2175, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 10299, 1, 1, 40, 2175, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 9010, 1, 2, 20, 0, 0, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 9010, 1, 1, 19, 0, 0, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 9010, 1, 0, 19, 0, 0, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 9010, 1, -1, 19, 0, 0, "", 1);// 13

		}

		public CheriPointsettaGarlandNSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriPointsettaGarlandNSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriPointsettaGarlandNSAddon();
			}
		}

		[Constructable]
		public CheriPointsettaGarlandNSAddonDeed()
		{
			Name = "CheriPointsettaGarlandNS";
		}

		public CheriPointsettaGarlandNSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}