
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriSinkCounterAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13511, 0, 0, 5}, {2253, 0, 0, 5}, {2254, 0, -1, 5}// 7	9	10	
			, {2252, -1, 0, 5}, {2251, -1, -1, 5}, {2519, 1, 0, 8}// 11	12	13	
			, {6867, 1, 0, 9}, {13511, 0, 1, 5}, {2253, 0, 1, 5}// 14	21	22	
			, {2252, -1, 1, 5}, {5637, 1, 1, 7}// 23	24	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriSinkCounterAddonDeed();
			}
		}

		[ Constructable ]
		public CheriSinkCounterAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4497, 1, -1, 1, 1061, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4497, 1, 0, 1, 1061, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3648, 1, 0, 0, 1117, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3648, 1, -1, 0, 1117, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1978, 0, 0, 0, 1095, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1978, 0, -1, 1, 1117, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6198, 0, 0, 4, 1069, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4497, 1, 1, 1, 1061, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 4497, 1, 2, 1, 1061, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3648, 1, 2, 0, 1117, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3648, 1, 1, 0, 1117, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1978, 0, 2, 0, 1117, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1978, 0, 1, 0, 1095, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2486, 1, 1, 8, 51, -1, "Potatoe Chips", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2484, 1, 1, 8, 51, -1, "Potatoe", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2484, 1, 1, 9, 51, -1, "Potatoe Chips", 1);// 27

		}

		public CheriSinkCounterAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriSinkCounterAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriSinkCounterAddon();
			}
		}

		[Constructable]
		public CheriSinkCounterAddonDeed()
		{
			Name = "CheriSinkCounter";
		}

		public CheriSinkCounterAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}