
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriCarolersAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriCarolersAddonDeed();
			}
		}

		[ Constructable ]
		public CheriCarolersAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3821, 0, 0, 23, 0, -1, "light", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3821, 0, 0, 3, 0, -1, "light", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3821, 0, 0, 17, 37, -1, "light", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3821, 0, 0, 9, 37, -1, "light", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4234, 0, 0, 15, 77, -1, "light", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4234, 0, 0, 0, 77, -1, "light", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4234, 0, 0, 8, 88, -1, "light", 1);// 7

		}

		public CheriCarolersAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriCarolersAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriCarolersAddon();
			}
		}

		[Constructable]
		public CheriCarolersAddonDeed()
		{
			Name = "CheriCarolers";
		}

		public CheriCarolersAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}