
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CheriCandleHolidaySm1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3235, -1, 0, 0}, {3234, 0, 0, 2}// 6	10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CheriCandleHolidaySm1AddonDeed();
			}
		}

		[ Constructable ]
		public CheriCandleHolidaySm1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5172, 0, 1, 12, 37, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 5164, 0, 1, 12, 37, 1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3882, 0, -1, 1, 37, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5168, -1, 0, 4, 1367, 1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3859, 1, 0, 12, 37, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3883, 0, 0, 6, 37, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3869, 0, 0, 6, 37, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3868, 0, 0, 5, 37, -1, "", 1);// 9

		}

		public CheriCandleHolidaySm1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CheriCandleHolidaySm1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CheriCandleHolidaySm1Addon();
			}
		}

		[Constructable]
		public CheriCandleHolidaySm1AddonDeed()
		{
			Name = "CheriCandleHolidaySm1";
		}

		public CheriCandleHolidaySm1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}