
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class cheriholidaycarriage1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6079, -2, -2, 5}, {6090, -3, 1, 5}, {6088, -3, 4, 5}// 1	2	3	
			, {6079, -2, 1, 5}, {6083, -2, -3, 5}, {6079, -2, 2, 5}// 4	5	6	
			, {6088, -2, 5, 5}, {6090, -3, 3, 5}, {6085, -2, -4, 5}// 7	8	9	
			, {6079, -2, 0, 5}, {6090, -3, 2, 5}, {6085, -3, -3, 5}// 10	11	12	
			, {6090, -3, -2, 5}, {6090, -3, -1, 5}, {6079, -2, -1, 5}// 13	14	15	
			, {6082, -2, 4, 5}, {6079, -2, 3, 5}, {6090, -3, 0, 5}// 16	18	20	
			, {6085, -2, -3, 5}, {6077, 0, -3, 5}, {6077, -1, 0, 5}// 21	25	27	
			, {6077, 0, -2, 5}, {6077, 0, 0, 5}, {6077, -1, -1, 5}// 28	30	31	
			, {6090, -1, -2, 5}, {3520, 1, 1, 18}, {6077, 1, -2, 5}// 32	38	40	
			, {6077, 0, -1, 5}, {6077, 0, 3, 5}, {6077, 0, 2, 5}// 42	46	50	
			, {6091, -1, -4, 5}, {6077, -1, 1, 5}, {6086, 2, -3, 5}// 51	53	55	
			, {6078, 0, 4, 5}, {6077, -1, 4, 5}, {6084, 1, -3, 5}// 56	58	59	
			, {6089, -1, 5, 5}, {6081, 1, 4, 5}, {3569, 1, 2, 42}// 60	62	63	
			, {6092, 2, 0, 5}, {6092, 2, 1, 5}, {6077, 1, 2, 5}// 64	65	66	
			, {6092, 2, -1, 5}, {6087, 1, 5, 5}, {6091, 0, -4, 5}// 67	68	70	
			, {3569, 1, 0, 19}, {15292, 0, 0, 13}, {15292, 2, 0, 12}// 71	73	74	
			, {6092, 2, 3, 5}, {6077, 0, 1, 5}, {6077, -1, 2, 5}// 75	78	79	
			, {6077, -1, 3, 5}, {6077, 1, 0, 5}, {6092, 2, 2, 5}// 81	83	84	
			, {6077, 1, -1, 5}, {6077, 1, 3, 5}, {6092, 2, -2, 5}// 88	89	91	
			, {6077, -1, -2, 5}, {6086, 1, -4, 5}, {6077, 1, 1, 5}// 93	94	95	
			, {6088, -1, 5, 5}, {6087, 2, 4, 5}, {6080, -1, -3, 5}// 97	100	101	
			, {6089, 0, 5, 5}// 102	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new cheriholidaycarriage1AddonDeed();
			}
		}

		[ Constructable ]
		public cheriholidaycarriage1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2852, -2, 3, 6, 0, 1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2272, -2, 3, 6, 1153, -1, "Snow Pile", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3664, 0, 1, 17, 1150, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2277, 3, 2, 21, 1153, -1, "Snow Pile", 1);// 23
			AddComplexComponent( (BaseAddon) this, 9010, 3, 0, 19, 0, 0, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 4234, -1, 4, 22, 88, -1, "light", 1);// 26
			AddComplexComponent( (BaseAddon) this, 15772, 1, 2, 18, 37, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 4234, -1, 4, 31, 74, -1, "light", 1);// 33
			AddComplexComponent( (BaseAddon) this, 4234, -1, 4, 15, 74, -1, "light", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3818, -1, 4, 24, 33, -1, "light", 1);// 35
			AddComplexComponent( (BaseAddon) this, 19591, 0, -1, 17, 1153, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2277, 3, 3, 26, 1153, -1, "Snow Pile", 1);// 37
			AddComplexComponent( (BaseAddon) this, 19590, 1, -1, 17, 1153, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 15772, 2, 2, 18, 37, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 3569, 1, 4, 22, 1150, -1, "rein", 1);// 43
			AddComplexComponent( (BaseAddon) this, 6815, -1, 4, 0, 0, -1, "garland", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2960, 0, -1, 5, 2955, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2277, 2, -1, 10, 1153, -1, "Snow Pile", 1);// 47
			AddComplexComponent( (BaseAddon) this, 15772, 0, -1, 8, 37, -1, "carriage top", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3665, 1, 1, 17, 1150, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 4117, 2, 2, 16, 1153, -1, "wheel", 1);// 52
			AddComplexComponent( (BaseAddon) this, 9010, 1, 1, 20, 0, 0, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 4117, -1, 1, 5, 1153, -1, "wheel", 1);// 57
			AddComplexComponent( (BaseAddon) this, 15772, 1, -1, 8, 37, -1, "carriage top", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3569, 0, 4, 21, 1150, -1, "rien", 1);// 69
			AddComplexComponent( (BaseAddon) this, 191, 0, 1, 14, 2955, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 3818, -1, 4, 31, 33, -1, "light", 1);// 76
			AddComplexComponent( (BaseAddon) this, 2278, 2, 0, 11, 1153, -1, "Snow Pile", 1);// 77
			AddComplexComponent( (BaseAddon) this, 2960, 0, 1, 5, 2955, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 4117, 1, -1, 5, 1153, -1, "wheel", 1);// 82
			AddComplexComponent( (BaseAddon) this, 3821, -1, 4, 39, 0, -1, "light", 1);// 85
			AddComplexComponent( (BaseAddon) this, 9004, 0, 2, 5, 37, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 3821, -1, 4, 17, 0, -1, "light", 1);// 87
			AddComplexComponent( (BaseAddon) this, 2277, -1, 1, 5, 1153, -1, "Snow Pile", 1);// 90
			AddComplexComponent( (BaseAddon) this, 190, 1, 1, 16, 1153, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 4117, -1, -1, 5, 1153, -1, "wheel", 1);// 96
			AddComplexComponent( (BaseAddon) this, 2960, 0, 0, 5, 2955, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 9010, 3, 1, 20, 0, 0, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 16382, 1, 4, 16, 1095, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 9010, 1, 0, 20, 0, 0, "", 1);// 104

		}

		public cheriholidaycarriage1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class cheriholidaycarriage1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new cheriholidaycarriage1Addon();
			}
		}

		[Constructable]
		public cheriholidaycarriage1AddonDeed()
		{
			Name = "cheriholidaycarriage1";
		}

		public cheriholidaycarriage1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}