/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CampfirePitAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CampfirePitAddonDeed();
			}
		}

		[ Constructable ]
		public CampfirePitAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3315 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 3316 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 3375 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3375 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 3319 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 3318 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 3317 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3319 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 3318 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3317 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 10749 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3315 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 3316 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3375 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 3375 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 7038 );
			AddComponent( ac, -2, -2, 0 );

		}

		public CampfirePitAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CampfirePitAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CampfirePitAddon();
			}
		}

		[Constructable]
		public CampfirePitAddonDeed()
		{
			Name = "CampfirePit";
		}

		public CampfirePitAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}