
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FlowerCartAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1244, -1, -1, 9}, {1244, -1, -2, 9}, {4119, -2, -1, 3}// 1	2	3	
			, {8631, -2, -1, 9}, {8631, -2, -2, 9}, {3206, -1, -1, 17}// 4	5	6	
			, {3233, -1, -2, 9}, {3210, -1, -2, 9}, {3204, -1, -2, 11}// 7	8	9	
			, {3209, -1, -1, 9}, {1244, -1, 0, 9}, {8631, -2, 0, 9}// 10	11	12	
			, {8630, -1, 0, 9}, {9036, -2, 0, 0}, {3265, -1, 1, 0}// 13	14	15	
			, {6811, -1, 0, 16}, {1244, 0, -2, 9}, {1244, 0, -1, 9}// 16	17	18	
			, {4119, 1, -1, 7}, {8631, 0, -1, 9}, {8631, 0, -2, 9}// 19	20	21	
			, {3206, 1, -2, 7}, {9037, 1, -1, 8}, {3241, 1, -2, 6}// 22	23	24	
			, {3265, 1, -2, 6}, {3380, 1, -2, 6}, {3237, 0, -1, 13}// 25	26	27	
			, {3236, 0, -1, 9}, {9327, 1, -2, 6}, {3367, 2, -1, 13}// 28	29	30	
			, {3370, 2, -1, 11}, {1244, 0, 0, 9}, {7127, 1, 3, 23}// 31	32	33	
			, {7127, 0, 1, 13}, {8631, 0, 0, 9}, {8630, 0, 0, 9}// 34	35	36	
			, {3237, 1, 0, 4}, {3214, 0, 1, 12}, {3208, 0, 1, 8}// 37	38	39	
			, {9036, 0, 0, 0}, {3223, 0, 0, 12}, {3256, 0, 0, 19}// 40	41	42	
			, {3203, 0, 0, 21}// 43	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FlowerCartAddonDeed();
			}
		}

		[ Constructable ]
		public FlowerCartAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public FlowerCartAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FlowerCartAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FlowerCartAddon();
			}
		}

		[Constructable]
		public FlowerCartAddonDeed()
		{
			Name = "FlowerCart";
		}

		public FlowerCartAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}