
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OldMiningCampAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1993, -3, -4, 0}, {1993, -2, -4, 0}, {1993, -1, -4, 0}// 1	2	3	
			, {1993, 0, -4, 0}, {1993, 1, -4, 0}, {1993, 2, -4, 0}// 4	5	6	
			, {1993, 3, -4, 0}, {167, -4, -4, 1}, {169, -4, -5, 0}// 7	8	9	
			, {168, -3, -5, 1}, {168, -2, -5, 1}, {168, 3, -5, 1}// 10	11	12	
			, {168, 0, -5, 1}, {168, 1, -5, 1}, {7045, -2, -4, 1}// 15	16	17	
			, {7046, -3, -4, 1}, {7050, -1, -4, 1}, {3091, 1, -4, 1}// 18	19	20	
			, {3129, 3, -4, 1}, {2473, 2, -4, 1}, {3711, 2, -4, 1}// 21	22	23	
			, {8564, -3, -4, 23}, {8564, -2, -4, 26}, {8564, -1, -4, 29}// 24	25	26	
			, {8560, 3, -4, 29}, {8560, 2, -4, 32}, {8564, 0, -4, 32}// 27	28	29	
			, {1474, 1, -4, 35}, {1993, -3, -3, 0}, {1993, -3, -2, 0}// 30	31	32	
			, {1993, -3, -1, 0}, {1993, -3, 0, 0}, {1993, -3, 1, 0}// 33	34	35	
			, {1993, -3, 2, 0}, {1993, -2, -3, 0}, {1993, -2, -2, 0}// 36	37	38	
			, {1993, -2, -1, 0}, {1993, -2, 0, 0}, {1993, -2, 1, 0}// 39	40	41	
			, {1993, -2, 2, 0}, {1993, -1, -3, 0}, {1993, -1, -2, 0}// 42	43	44	
			, {1993, -1, -1, 0}, {1993, -1, 0, 0}, {1993, -1, 1, 0}// 45	46	47	
			, {1993, -1, 2, 0}, {1993, 0, -3, 0}, {1993, 0, -2, 0}// 48	49	50	
			, {1993, 0, -1, 0}, {1993, 0, 0, 0}, {1993, 0, 1, 0}// 51	52	53	
			, {1993, 0, 2, 0}, {1993, 1, -3, 0}, {1993, 1, -2, 0}// 54	55	56	
			, {1993, 1, -1, 0}, {1993, 1, 0, 0}, {1993, 1, 1, 0}// 57	58	59	
			, {1993, 1, 2, 0}, {1993, 2, -3, 0}, {1993, 2, -2, 0}// 60	61	62	
			, {1993, 2, -1, 0}, {1993, 2, 0, 0}, {1993, 2, 1, 0}// 63	64	65	
			, {1993, 2, 2, 0}, {1993, 3, -3, 0}, {1993, 3, -2, 0}// 66	67	68	
			, {1993, 3, -1, 0}, {1993, 3, 0, 0}, {1993, 3, 1, 0}// 69	70	71	
			, {1993, 3, 2, 0}, {1993, -3, 3, 0}, {1993, -2, 3, 0}// 72	73	74	
			, {1993, -1, 3, 0}, {1993, 0, 3, 0}, {1993, 1, 3, 0}// 75	76	77	
			, {1993, 2, 3, 0}, {1993, 3, 3, 0}, {167, -4, 3, 1}// 78	79	80	
			, {168, -3, 3, 1}, {167, -4, -3, 1}, {167, -4, 2, 1}// 81	82	83	
			, {8662, -4, -1, 1}, {8662, -4, 0, 1}, {1718, 1, 4, 1}// 84	85	92	
			, {1725, -1, 3, 1}, {7042, -3, -3, 1}, {7043, -2, -3, 1}// 93	94	95	
			, {7051, -1, -3, 1}, {7052, -1, -3, 1}, {7044, -2, -2, 1}// 96	97	98	
			, {7045, -3, -2, 1}, {7046, -3, -3, 1}, {7047, -2, -3, 1}// 99	100	101	
			, {7048, -2, -2, 1}, {3892, -2, -3, 2}, {3893, -1, -3, 2}// 102	103	104	
			, {3893, -2, -2, 1}, {2880, -3, 1, 1}, {2880, -3, 0, 1}// 105	106	107	
			, {2929, 1, 0, 1}, {2930, 1, -1, 1}, {2928, 1, 0, 1}// 108	109	110	
			, {3088, 2, 0, 1}, {3089, 1, 1, 1}, {2519, -3, 1, 7}// 111	112	113	
			, {2519, -3, 1, 8}, {2524, -3, 0, 7}, {2585, 1, -1, 7}// 114	115	116	
			, {2467, 1, 0, 7}, {2597, 1, 0, 7}, {8564, -3, 4, 23}// 117	118	119	
			, {8564, -3, -3, 23}, {8564, -3, -2, 23}, {8564, -3, -1, 23}// 120	121	122	
			, {8564, -3, 0, 23}, {8564, -3, 1, 23}, {8564, -3, 2, 23}// 123	124	125	
			, {8564, -3, 3, 23}, {8564, -2, 4, 26}, {8564, -2, -3, 26}// 126	127	128	
			, {8564, -2, -1, 26}, {8564, -2, 0, 26}, {8564, -2, 1, 26}// 129	130	131	
			, {8564, -2, 2, 26}, {8564, -2, 3, 26}, {8564, -1, 4, 29}// 132	133	134	
			, {8564, -1, -3, 29}, {8564, -1, -2, 29}, {8564, -1, -1, 29}// 135	136	137	
			, {8564, -1, 0, 29}, {8564, -1, 1, 29}, {8564, -1, 2, 29}// 138	139	140	
			, {8564, -1, 3, 29}, {8560, 3, 4, 29}, {8560, 3, -3, 29}// 141	142	143	
			, {8560, 3, -2, 29}, {8560, 3, -1, 29}, {8560, 3, 1, 29}// 144	145	146	
			, {8560, 3, 2, 29}, {8560, 3, 3, 29}, {8560, 2, 4, 32}// 147	148	149	
			, {8560, 2, -3, 32}, {8560, 2, -2, 32}, {8560, 2, -1, 32}// 150	151	152	
			, {8560, 2, 0, 32}, {8560, 2, 1, 32}, {8560, 2, 2, 32}// 153	154	155	
			, {8560, 2, 3, 32}, {8564, 0, 4, 32}, {8564, 0, -3, 32}// 156	157	158	
			, {8564, 0, -2, 32}, {8564, 0, -1, 32}, {8564, 0, 0, 32}// 159	160	161	
			, {8564, 0, 1, 32}, {8564, 0, 2, 32}, {8564, 0, 3, 32}// 162	163	164	
			, {1474, 1, 4, 35}, {1474, 1, -3, 35}, {1474, 1, -2, 35}// 165	166	167	
			, {1474, 1, -1, 35}, {1474, 1, 0, 35}, {1474, 1, 1, 35}// 168	169	170	
			, {1474, 1, 2, 35}, {1474, 1, 3, 35}, {8562, 3, 1, 30}// 171	172	173	
			, {8566, -1, -2, 30}, {183, 0, 3, 21}, {183, 1, 3, 21}// 174	175	176	
			, {183, 2, 3, 21}, {183, -1, 3, 21}, {191, -2, 3, 21}// 177	178	179	
			, {191, 3, 3, 21}, {3897, -2, 4, 0}, {3717, -3, 4, 0}// 180	181	182	
			, {3718, -2, 4, 0}, {3898, -2, 5, 0}, {2597, -2, 4, 0}// 183	184	185	
			, {3245, 3, 4, 0}, {3246, -3, 4, 0}, {3249, -1, 4, 0}// 186	187	188	
			, {3250, 2, 4, 0}, {1993, 4, -4, 0}, {168, 4, -5, 1}// 189	190	191	
			, {167, 4, -4, 1}, {8560, 5, -4, 23}, {8560, 4, -4, 26}// 192	193	194	
			, {3251, 5, -4, 0}, {1993, 4, -3, 0}, {1993, 4, -2, 0}// 195	196	197	
			, {1993, 4, -1, 0}, {1993, 4, 0, 0}, {1993, 4, 1, 0}// 198	199	200	
			, {1993, 4, 2, 0}, {1993, 4, 3, 0}, {166, 4, 3, 1}// 201	202	203	
			, {167, 4, -3, 1}, {167, 4, 2, 1}, {167, 4, -1, 1}// 204	205	206	
			, {8662, 4, 0, 1}, {8560, 5, 4, 23}, {8560, 5, -3, 23}// 207	210	211	
			, {8560, 5, -2, 23}, {8560, 5, -1, 23}, {8560, 5, 0, 23}// 212	213	214	
			, {8560, 5, 1, 23}, {8560, 5, 2, 23}, {8560, 5, 3, 23}// 215	216	217	
			, {8560, 4, 4, 26}, {8560, 4, -3, 26}, {8560, 4, -2, 26}// 218	219	220	
			, {8560, 4, -1, 26}, {8560, 4, 0, 26}, {8560, 4, 1, 26}// 221	222	223	
			, {8560, 4, 2, 26}, {8560, 4, 3, 26}, {3244, 5, -2, 0}// 224	225	226	
			, {3247, 5, 0, 0}, {3248, 4, 4, 0}, {3252, 5, -1, 0}// 227	228	229	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OldMiningCampAddonDeed();
			}
		}

		[ Constructable ]
		public OldMiningCampAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 186, -1, -5, 1, 0, 1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 186, 2, -5, 1, 0, 1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 185, -4, 1, 1, 0, 1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 185, -4, -2, 1, 0, 1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 186, -1, 3, 1, 0, 1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 186, 2, 3, 1, 0, 1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 186, -2, 3, 1, 0, 1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 186, 3, 3, 1, 0, 1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 185, 4, 1, 1, 0, 1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 185, 4, -2, 1, 0, 1, "", 1);// 209

		}

		public OldMiningCampAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OldMiningCampAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OldMiningCampAddon();
			}
		}

		[Constructable]
		public OldMiningCampAddonDeed()
		{
			Name = "OldMiningCamp";
		}

		public OldMiningCampAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}