
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace KittensIceSkatingPond
{
	public class KittensIceSkatingPondAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2186, -5, -7, 2}, {2186, -4, -7, 2}, {2186, -3, -7, 2}// 1	2	3	
			, {2186, -2, -7, 2}, {2186, -1, -7, 2}, {2186, 0, -7, 2}// 4	5	6	
			, {2186, 1, -7, 2}, {2186, 2, -7, 2}, {2186, 3, -7, 2}// 7	8	9	
			, {2186, 4, -7, 2}, {2186, -6, -7, 2}, {6077, -5, -5, 2}// 10	11	76	
			, {6077, -4, -5, 2}, {6077, -3, -5, 2}, {6077, -2, -5, 2}// 77	78	79	
			, {6077, -1, -5, 2}, {6077, 0, -5, 2}, {6077, 1, -5, 2}// 80	81	82	
			, {6077, 2, -5, 2}, {6077, 3, -5, 2}, {6077, 4, -5, 2}// 83	84	85	
			, {6077, -5, -5, 2}, {6077, -5, -4, 2}, {6077, -5, -3, 2}// 86	87	88	
			, {6077, -5, -2, 2}, {6077, -5, -1, 2}, {6077, -5, 0, 2}// 89	90	91	
			, {6077, -5, 1, 2}, {6077, -5, 2, 2}, {6077, -5, 3, 2}// 92	93	94	
			, {6077, -5, 4, 2}, {6077, -5, 5, 2}, {6077, -5, 7, 2}// 95	96	97	
			, {6077, -5, 7, 2}, {6077, -4, 7, 2}, {6077, -3, 7, 2}// 98	99	100	
			, {6077, -2, 7, 2}, {6077, -1, 7, 2}, {6077, 0, 7, 2}// 101	102	103	
			, {6077, 1, 7, 2}, {6077, 2, 7, 2}, {6077, 3, 7, 2}// 104	105	106	
			, {6077, 4, 7, 2}, {6077, -4, -4, 2}, {6077, -3, -4, 2}// 107	108	109	
			, {6077, -2, -4, 2}, {6077, -1, -4, 2}, {6077, 0, -4, 2}// 110	111	112	
			, {6077, 1, -4, 2}, {6077, 2, -4, 2}, {6077, 3, -4, 2}// 113	114	115	
			, {6077, 4, -4, 2}, {6077, -4, -3, 2}, {6077, -4, -2, 2}// 116	117	118	
			, {6077, -4, -1, 2}, {6077, -4, 0, 2}, {6077, -4, 1, 2}// 119	120	121	
			, {6077, -4, 2, 2}, {6077, -4, 3, 2}, {6077, -4, 4, 2}// 122	123	124	
			, {6077, -4, 5, 2}, {6077, -3, 5, 2}, {6077, -2, 5, 2}// 125	126	127	
			, {6077, -1, 5, 2}, {6077, 0, 5, 2}, {6077, 1, 5, 2}// 128	129	130	
			, {6077, 2, 5, 2}, {6077, 3, 5, 2}, {6077, 4, 5, 2}// 131	132	133	
			, {2186, -5, 7, 2}, {2186, -4, 7, 2}, {2186, -3, 7, 2}// 160	161	162	
			, {2186, -2, 7, 2}, {2186, -1, 7, 2}, {2186, 0, 7, 2}// 163	164	165	
			, {2186, 1, 7, 2}, {2186, 2, 7, 2}, {2186, 3, 7, 2}// 166	167	168	
			, {2186, 4, 7, 2}, {2187, -7, -5, 2}, {2187, -7, -4, 2}// 169	170	171	
			, {2187, -7, -3, 2}, {2187, -7, -2, 2}, {2187, -7, -1, 2}// 172	173	174	
			, {2187, -7, 0, 2}, {2187, -7, 1, 2}, {2187, -7, 2, 2}// 175	176	177	
			, {2187, -7, 3, 2}, {2187, -7, 4, 2}, {2187, -7, 5, 2}// 178	179	180	
			, {2187, -7, 6, 2}, {2860, -5, 4, 2}, {2860, -5, 0, 2}// 181	182	183	
			, {2860, -5, -3, 2}, {2861, -3, -5, 2}, {2861, 0, -5, 2}// 184	185	186	
			, {2861, 1, -5, 2}, {2860, -5, 1, 2}, {6077, -5, -6, 2}// 187	188	189	
			, {6077, -4, -6, 2}, {6077, -3, -6, 2}, {6077, -2, -6, 2}// 190	191	192	
			, {6077, -1, -6, 2}, {6077, 0, -6, 2}, {6077, 1, -6, 2}// 193	194	195	
			, {6077, 2, -6, 2}, {6077, 3, -6, 2}, {6077, 4, -6, 2}// 196	197	198	
			, {6077, -5, 6, 2}, {6077, -4, 6, 2}, {6077, -3, 6, 2}// 199	200	201	
			, {6077, -2, 6, 2}, {6077, -1, 6, 2}, {6077, 0, 6, 2}// 202	203	204	
			, {6077, 1, 6, 2}, {6077, 2, 6, 2}, {6077, 3, 6, 2}// 205	206	207	
			, {6077, 4, 6, 2}, {6077, -6, -6, 2}, {6077, -6, -5, 2}// 208	209	210	
			, {6077, -6, -4, 2}, {6077, -6, -3, 2}, {6077, -6, -2, 2}// 211	212	213	
			, {6077, -6, -1, 2}, {6077, -6, 0, 2}, {6077, -6, 1, 2}// 214	215	216	
			, {6077, -6, 2, 2}, {6077, -6, 3, 2}, {6077, -6, 4, 2}// 217	218	219	
			, {6077, -6, 5, 2}, {6077, -6, 6, 2}, {6077, -6, 7, 2}// 220	221	222	
			, {2187, -7, -6, 2}, {2187, -7, 7, 2}, {2186, -6, 7, 2}// 223	224	225	
			, {2861, 4, -5, 2}, {17778, -6, 8, 0}, {17778, -5, 8, 0}// 232	233	234	
			, {17778, -4, 8, 0}, {17778, -3, 8, 0}, {17778, -2, 8, 0}// 235	236	237	
			, {17778, -1, 8, 0}, {17778, 0, 8, 0}, {17778, 1, 8, 0}// 238	239	240	
			, {17778, 2, 8, 0}, {17778, 3, 8, 0}, {17778, 4, 8, 0}// 241	242	243	
			, {17778, -5, -6, 0}, {17778, -4, -6, 0}, {17778, -6, -6, 0}// 244	245	246	
			, {17778, -3, -6, 0}, {17778, -2, -6, 0}, {17778, -1, -6, 0}// 247	248	249	
			, {17778, 0, -6, 0}, {17778, 1, -6, 0}, {17778, 2, -6, 0}// 250	251	252	
			, {17778, 3, -6, 0}, {17778, 4, -6, 0}, {17781, -5, 8, 11}// 253	254	255	
			, {17781, -6, 6, 0}, {17781, -6, 5, 0}, {17781, -6, 3, 0}// 256	257	258	
			, {17781, -6, 2, 0}, {17781, -6, 1, 0}, {17781, -6, 0, 0}// 259	260	261	
			, {17781, -6, 4, 0}, {17781, -6, -1, 0}, {17781, -6, -2, 0}// 262	263	264	
			, {17781, -6, -3, 0}, {17781, -6, -4, 0}, {17781, -6, -5, 0}// 265	266	267	
			, {17781, -6, -6, 0}, {2186, 5, -7, 2}, {2186, 6, -7, 2}// 268	271	272	
			, {2186, 7, -7, 2}, {6077, 5, -5, 2}, {6077, 6, -5, 2}// 273	274	275	
			, {6077, 5, 7, 2}, {6077, 6, 7, 2}, {6077, 6, -4, 2}// 276	277	278	
			, {6077, 6, -3, 2}, {6077, 6, -2, 2}, {6077, 6, -1, 2}// 279	280	281	
			, {6077, 6, 0, 2}, {6077, 6, 1, 2}, {6077, 6, 2, 2}// 282	283	284	
			, {6077, 6, 3, 2}, {6077, 6, 4, 2}, {6077, 6, 5, 2}// 285	286	287	
			, {6077, 5, -4, 2}, {6077, 5, -3, 2}, {6077, 5, -2, 2}// 288	289	290	
			, {6077, 5, -1, 2}, {6077, 5, 0, 2}, {6077, 5, 1, 2}// 291	292	293	
			, {6077, 5, 2, 2}, {6077, 5, 3, 2}, {6077, 5, 4, 2}// 294	295	296	
			, {6077, 5, 5, 2}, {2186, 5, 7, 2}, {2186, 6, 7, 2}// 297	308	309	
			, {6077, 5, -6, 2}, {6077, 6, -6, 2}, {6077, 5, 6, 2}// 310	311	312	
			, {6077, 6, 6, 2}, {6077, 7, -6, 2}, {6077, 7, -5, 2}// 313	314	315	
			, {6077, 7, -4, 2}, {6077, 7, -3, 2}, {6077, 7, -2, 2}// 316	317	318	
			, {6077, 7, -1, 2}, {6077, 7, 0, 2}, {6077, 7, 1, 2}// 319	320	321	
			, {6077, 7, 2, 2}, {6077, 7, 3, 2}, {6077, 7, 4, 2}// 322	323	324	
			, {6077, 7, 5, 2}, {6077, 7, 6, 2}, {6077, 7, 7, 2}// 325	326	327	
			, {2186, 7, 7, 2}, {2187, 7, -6, 2}, {2187, 7, -5, 2}// 328	329	330	
			, {2187, 7, -4, 2}, {2187, 7, -3, 2}, {2187, 7, -2, 2}// 331	332	333	
			, {2187, 7, 3, 2}, {2187, 7, 4, 2}, {2187, 7, 5, 2}// 334	335	336	
			, {2187, 7, 6, 2}, {2187, 7, 7, 2}, {17778, 5, 8, 0}// 337	338	348	
			, {17778, 6, 8, 0}, {17778, 7, 8, 0}, {17778, 5, -6, 0}// 349	350	351	
			, {17778, 6, -6, 0}, {17778, 7, -6, 0}, {17781, 8, -2, 2}// 352	353	354	
			, {17781, 8, -3, 2}, {17781, 8, -4, 2}, {17781, 8, -5, 2}// 355	356	357	
			, {17781, 8, -6, 2}, {17781, 8, 3, 2}, {17781, 8, 4, 2}// 358	359	360	
			, {17781, 8, 5, 2}, {17781, 8, 6, 2}, {17781, 8, 7, 2}// 361	362	363	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KittensIceSkatingPondAddonDeed();
			}
		}

		[ Constructable ]
		public KittensIceSkatingPondAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6077, -3, -3, 2, 1151, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6077, -3, -2, 2, 1151, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6077, -3, -1, 2, 1151, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6077, -3, 0, 2, 1151, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6077, -3, 1, 2, 1151, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6077, -3, 2, 2, 1151, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6077, -3, 3, 2, 1151, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6077, -3, 4, 2, 1151, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6077, -2, -3, 2, 1151, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6077, -2, -2, 2, 1151, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6077, -2, -1, 2, 1151, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6077, -2, 0, 2, 1151, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6077, -2, 1, 2, 1151, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6077, -2, 2, 2, 1151, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6077, -2, 3, 2, 1151, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6077, -2, 4, 2, 1151, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6077, -1, -3, 2, 1151, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6077, -1, -2, 2, 1151, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 6077, -1, -1, 2, 1151, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 6077, -1, 0, 2, 1151, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 6077, -1, 1, 2, 1151, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 6077, -1, 2, 2, 1151, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 6077, -1, 3, 2, 1151, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 6077, -1, 4, 2, 1151, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 6077, 0, -3, 2, 1151, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 6077, 0, -2, 2, 1151, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 6077, 0, -1, 2, 1151, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 6077, 0, 0, 2, 1151, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 6077, 0, 1, 2, 1151, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 6077, 0, 2, 2, 1151, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 6077, 0, 3, 2, 1151, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 6077, 0, 4, 2, 1151, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 6077, 1, -3, 2, 1151, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 6077, 1, -2, 2, 1151, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6077, 1, -1, 2, 1151, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 6077, 1, 0, 2, 1151, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6077, 1, 1, 2, 1151, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 6077, 1, 2, 2, 1151, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 6077, 1, 3, 2, 1151, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 6077, 1, 4, 2, 1151, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 6077, 2, -3, 2, 1151, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 6077, 2, -2, 2, 1151, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 6077, 2, -1, 2, 1151, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 6077, 2, 0, 2, 1151, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 6077, 2, 1, 2, 1151, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 6077, 2, 2, 2, 1151, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 6077, 2, 3, 2, 1151, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 6077, 2, 4, 2, 1151, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 6077, 3, -3, 2, 1151, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 6077, 3, -2, 2, 1151, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 6077, 3, -1, 2, 1151, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 6077, 3, 0, 2, 1151, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6077, 3, 1, 2, 1151, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 6077, 3, 2, 2, 1151, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6077, 3, 3, 2, 1151, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 6077, 3, 4, 2, 1151, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 6077, 4, -3, 2, 1151, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 6077, 4, -2, 2, 1151, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 6077, 4, -1, 2, 1151, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 6077, 4, 0, 2, 1151, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 6077, 4, 1, 2, 1151, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 6077, 4, 2, 2, 1151, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 6077, 4, 3, 2, 1151, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 6077, 4, 4, 2, 1151, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 6089, -3, 5, 2, 1151, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 6089, -2, 5, 2, 1151, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 6089, -1, 5, 2, 1151, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 6089, 0, 5, 2, 1151, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 6089, 1, 5, 2, 1151, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 6089, 2, 5, 2, 1151, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 6089, 3, 5, 2, 1151, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 6089, 4, 5, 2, 1151, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 6090, -4, -3, 2, 1151, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 6090, -4, -2, 2, 1151, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 6090, -4, -1, 2, 1151, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 6090, -4, 0, 2, 1151, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 6090, -4, 1, 2, 1151, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 6090, -4, 2, 2, 1151, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 6090, -4, 3, 2, 1151, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 6090, -4, 4, 2, 1151, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 6091, -3, -4, 2, 1151, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 6091, -2, -4, 2, 1151, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 6091, -1, -4, 2, 1151, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 6091, 0, -4, 2, 1151, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 6091, 1, -4, 2, 1151, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 6091, 2, -4, 2, 1151, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 6091, 3, -4, 2, 1151, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 6091, 4, -4, 2, 1151, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 6088, -4, 5, 2, 1151, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 6085, -4, -4, 2, 1151, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 2852, -6, 6, 2, 0, 43, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 9077, -5, 7, 2, 38, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 9076, -5, 7, 2, 38, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 2852, -6, -6, 2, 0, 43, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 9077, -5, -5, 2, 38, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 9076, -5, -5, 2, 38, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 9001, -6, -4, 2, 1368, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 9000, -4, -6, 2, 38, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 6092, 5, -3, 2, 1151, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 6092, 5, -2, 2, 1151, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 6092, 5, -1, 2, 1151, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 6092, 5, 0, 2, 1151, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 6092, 5, 1, 2, 1151, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 6092, 5, 2, 2, 1151, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 6092, 5, 3, 2, 1151, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 6092, 5, 4, 2, 1151, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 6087, 5, 5, 2, 1151, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 6086, 5, -4, 2, 1151, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 2852, 7, -1, 2, 0, 43, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 9077, 8, 0, 2, 38, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 9076, 8, 0, 2, 38, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 2852, 7, 2, 2, 0, 43, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 9077, 8, 3, 2, 38, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 9076, 8, 3, 2, 38, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 2852, 6, -6, 2, 0, 43, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 9077, 7, -5, 2, 38, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 9076, 7, -5, 2, 38, -1, "", 1);// 347

		}

		public KittensIceSkatingPondAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KittensIceSkatingPondAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KittensIceSkatingPondAddon();
			}
		}

		[Constructable]
		public KittensIceSkatingPondAddonDeed()
		{
			Name = "KittensIceSkatingPond";
		}

		public KittensIceSkatingPondAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}