
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace ChristmasGarlandLights
{
	public class ChristmasGarlandLightsAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9017, -1, 0, 1}, {9017, 0, 0, 0}, {9017, 2, 0, 0}// 2	3	8	
			, {9017, 1, 0, 0}// 9	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ChristmasGarlandLightsAddonDeed();
			}
		}

		[ Constructable ]
		public ChristmasGarlandLightsAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 15291, 0, 0, 1, 272, -1, "Holiday Garland", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9014, -1, 0, 1, 0, 0, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9014, 0, 0, 0, 0, 0, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 15291, 2, 0, 1, 272, -1, "Holiday Garland", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9004, 1, 1, 7, 33, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 9014, 1, 0, 1, 0, 0, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 9014, 2, 0, 1, 0, 0, "", 1);// 11

		}

		public ChristmasGarlandLightsAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ChristmasGarlandLightsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ChristmasGarlandLightsAddon();
			}
		}

		[Constructable]
		public ChristmasGarlandLightsAddonDeed()
		{
			Name = "ChristmasGarlandLights";
		}

		public ChristmasGarlandLightsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}