
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class christreeAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new christreeAddonDeed();
			}
		}

		[ Constructable ]
		public christreeAddon()
		{



			AddComplexComponent( (BaseAddon) this, 7955, 3, -1, 0, 0, -1, "PremiumSpawner", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7955, -1, 1, 0, 0, -1, "PremiumSpawner", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4795, 2, -2, 0, 172, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4792, -1, 1, 0, 38, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4789, -3, 2, 0, 1083, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4805, 4, -2, 12, 48, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4802, 1, 1, 12, 7, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4804, 3, -1, 12, 38, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4803, 2, 0, 12, 103, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 4801, 0, 2, 12, 172, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4794, 1, -1, 0, 53, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4793, 0, 0, 0, 48, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 4806, 4, -3, 12, 53, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 4800, -1, 3, 12, 54, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 4799, -2, 3, 12, 48, -1, "", 1);// 15

		}

		public christreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class christreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new christreeAddon();
			}
		}

		[Constructable]
		public christreeAddonDeed()
		{
			Name = "christree";
		}

		public christreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}