
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace DocsPool
{
	public class DocsPoolAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6277, 0, 2, 4}, {6277, 0, 1, 5}// 88	91	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DocsPoolAddonDeed();
			}
		}

		[ Constructable ]
		public DocsPoolAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1801, -4, -4, 0, 1153, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1801, -4, -3, 0, 1153, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1801, -4, -2, 0, 1153, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1801, -4, -1, 0, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1801, -4, 0, 0, 1153, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1801, -4, 1, 0, 1153, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1801, -4, 2, 0, 1153, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1801, -4, 3, 0, 1153, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1801, -3, -4, 0, 1153, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1801, -2, -4, 0, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1801, -1, -4, 0, 1153, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 13410, -3, -3, 4, 98, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 13410, -3, -2, 4, 98, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 13410, -3, -1, 4, 98, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13410, -3, 0, 4, 98, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 13410, -3, 1, 4, 98, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 13410, -3, 2, 4, 98, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13410, -3, 3, 4, 98, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13410, -2, -3, 4, 98, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13410, -2, -2, 4, 98, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 13410, -2, -1, 4, 98, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 13410, -2, 0, 4, 98, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 13410, -2, 1, 4, 98, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 13410, -2, 2, 4, 98, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13410, -2, 3, 4, 98, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 13410, -1, -3, 4, 98, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 13410, -1, -2, 4, 98, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13410, -1, -1, 4, 98, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13410, -1, 0, 4, 98, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 13410, -1, 1, 4, 98, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13410, -1, 2, 4, 98, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 13410, -1, 3, 4, 98, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1801, -4, 4, 0, 1153, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1801, -4, 5, 0, 1153, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1801, -3, 5, 0, 1153, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1801, -2, 5, 0, 1153, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1801, -1, 5, 0, 1153, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 13410, -3, 4, 4, 98, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 13410, -2, 4, 4, 98, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13410, -1, 4, 4, 98, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1801, 4, -4, 0, 1153, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1801, 4, -3, 0, 1153, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1801, 4, -2, 0, 1153, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1801, 4, -1, 0, 1153, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1801, 4, 0, 0, 1153, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1801, 4, 1, 0, 1153, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1801, 4, 2, 0, 1153, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1801, 4, 3, 0, 1153, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1801, 0, -4, 0, 1153, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1801, 1, -4, 0, 1153, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1801, 2, -4, 0, 1153, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1801, 3, -4, 0, 1153, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1803, 5, 1, 0, 1153, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1803, 5, 0, 0, 1153, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1803, 5, 2, 0, 1153, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1803, 5, -1, 0, 1153, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1801, 5, -2, 0, 1153, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1801, 5, 3, 0, 1153, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 13410, 0, -3, 4, 98, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 13410, 0, -2, 4, 98, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 13410, 0, -1, 4, 98, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 13410, 0, 0, 4, 98, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 13410, 0, 1, 4, 98, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 13410, 0, 2, 4, 98, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 13410, 0, 3, 4, 98, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 13410, 1, -3, 4, 98, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 13410, 1, -2, 4, 98, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 13410, 1, -1, 4, 98, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 13410, 1, 0, 4, 98, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 13410, 1, 1, 4, 98, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 13410, 1, 2, 4, 98, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 13410, 1, 3, 4, 98, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 13410, 2, -3, 4, 98, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 13410, 2, -2, 4, 98, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 13410, 2, -1, 4, 98, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 13410, 2, 0, 4, 98, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 13410, 2, 1, 4, 98, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 13410, 2, 2, 4, 98, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 13410, 2, 3, 4, 98, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 13410, 3, -3, 4, 98, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 13410, 3, -2, 4, 98, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 13410, 3, -1, 4, 98, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 13410, 3, 0, 4, 98, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 13410, 3, 1, 4, 98, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 13410, 3, 2, 4, 98, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 13410, 3, 3, 4, 98, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1981, 0, 1, 4, 72, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 2031, 1, 2, 15, 1083, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 5632, 0, 1, 6, 1, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1801, 4, 4, 0, 1153, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1801, 4, 5, 0, 1153, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1801, 0, 5, 0, 1153, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1801, 1, 5, 0, 1153, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1801, 2, 5, 0, 1153, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1801, 3, 5, 0, 1153, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 13410, 0, 4, 4, 98, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 13410, 1, 4, 4, 98, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 13410, 2, 4, 4, 98, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 13410, 3, 4, 4, 98, -1, "", 1);// 101

		}

		public DocsPoolAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DocsPoolAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DocsPoolAddon();
			}
		}

		[Constructable]
		public DocsPoolAddonDeed()
		{
			Name = "DocsPool";
		}

		public DocsPoolAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}