/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FishStationSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FishStationSouthAddonDeed();
			}
		}

		[ Constructable ]
		public FishStationSouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4100 );
			ac.Name = "Water Tap";
			AddComponent( ac, -1, 0, 16 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4651 );
			AddComponent( ac, 1, 0, 6 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 7705 );
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 22 );
			AddComponent( ac, 2, -1, 10 );
			ac = new AddonComponent( 22 );
			AddComponent( ac, -1, -1, 10 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2880 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 22 );
			AddComponent( ac, 1, -1, 10 );
			ac = new AddonComponent( 7707 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7703 );
			AddComponent( ac, 2, 0, 8 );
			ac = new AddonComponent( 22 );
			AddComponent( ac, 0, -1, 10 );
			ac = new AddonComponent( 3059 );
			ac.Name = "Catch Cleaning Station";
			AddComponent( ac, 2, 0, 4 );
			ac = new AddonComponent( 2879 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 25 );
			AddComponent( ac, -2, 0, 10 );
			ac = new AddonComponent( 2879 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3544 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2883 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 2884 );
			AddComponent( ac, 0, 0, 7 );

		}

		public FishStationSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FishStationSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FishStationSouthAddon();
			}
		}

		[Constructable]
		public FishStationSouthAddonDeed()
		{
			Name = "FishStationSouth";
		}

		public FishStationSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}