
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Hearse
{
	public class HearseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3937, -1, -1, 15}, {2866, -1, 1, 13}, {3568, 3, 2, 58}// 16	38	56	
			, {3568, 2, 2, 58}, {3311, 1, -2, 8}, {3311, 1, -2, 8}// 57	62	66	
			, {3311, 1, -1, 8}, {3311, 1, -3, 8}, {3311, 1, -1, 8}// 70	74	78	
			, {3311, 1, 0, 8}, {3311, -2, 0, 8}// 82	87	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HearseAddonDeed();
			}
		}

		[ Constructable ]
		public HearseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1997, -2, -3, 12, 1083, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1997, -2, -2, 12, 1083, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1997, -2, -1, 12, 1083, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1997, -2, 0, 12, 1083, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1997, -2, 1, 12, 1083, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1997, -1, -3, 12, 1083, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1997, -1, -2, 12, 1083, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1997, -1, -1, 12, 1083, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1997, -1, 0, 12, 1083, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1997, -1, 1, 12, 1083, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1997, 0, -3, 12, 1083, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1997, 0, -2, 12, 1083, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1997, 0, -1, 12, 1083, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1997, 0, 0, 12, 1083, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1997, 0, 1, 12, 1083, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7220, -2, 0, 13, 1102, -1, "Coffin", 1);// 17
			AddComplexComponent( (BaseAddon) this, 7221, -1, 0, 13, 1102, -1, "Coffin", 1);// 18
			AddComplexComponent( (BaseAddon) this, 7222, -1, -1, 13, 1102, -1, "Coffin", 1);// 19
			AddComplexComponent( (BaseAddon) this, 7222, -1, -2, 13, 1102, -1, "Coffin", 1);// 20
			AddComplexComponent( (BaseAddon) this, 7223, -1, -3, 13, 1102, -1, "Coffin", 1);// 21
			AddComplexComponent( (BaseAddon) this, 7227, -2, 0, 13, 1102, -1, "Coffin", 1);// 22
			AddComplexComponent( (BaseAddon) this, 7219, -1, 0, 26, 1106, -1, "Coffin", 1);// 23
			AddComplexComponent( (BaseAddon) this, 7219, -2, -3, 13, 1103, -1, "Coffin", 1);// 24
			AddComplexComponent( (BaseAddon) this, 7219, -2, -2, 13, 1103, -1, "Coffin", 1);// 25
			AddComplexComponent( (BaseAddon) this, 7216, -1, -2, 25, 1106, -1, "Coffin", 1);// 26
			AddComplexComponent( (BaseAddon) this, 7216, -1, -1, 25, 1106, -1, "Coffin", 1);// 27
			AddComplexComponent( (BaseAddon) this, 7216, -1, 0, 25, 1106, -1, "Coffin", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7219, -1, -2, 26, 1106, -1, "Coffin", 1);// 29
			AddComplexComponent( (BaseAddon) this, 7219, -1, -1, 26, 1106, -1, "Coffin", 1);// 30
			AddComplexComponent( (BaseAddon) this, 7219, -1, 0, 24, 1103, -1, "Coffin", 1);// 31
			AddComplexComponent( (BaseAddon) this, 7218, -2, -1, 15, 1103, -1, "Coffin", 1);// 32
			AddComplexComponent( (BaseAddon) this, 7565, -1, -1, 17, 0, -1, "Mummy", 1);// 33
			AddComplexComponent( (BaseAddon) this, 7944, -1, 0, 17, 1150, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 7946, -1, -1, 15, 1150, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 15285, -1, 0, 18, 0, -1, "Ankh Pendant", 1);// 36
			AddComplexComponent( (BaseAddon) this, 7341, -1, -2, 17, 0, -1, "Mummy", 1);// 37
			AddComplexComponent( (BaseAddon) this, 5485, 2, -1, 11, 1083, -1, "wheel", 1);// 39
			AddComplexComponent( (BaseAddon) this, 5485, 2, 1, 11, 1083, -1, "wheel", 1);// 40
			AddComplexComponent( (BaseAddon) this, 5485, -2, 1, 7, 1083, -1, "wheel", 1);// 41
			AddComplexComponent( (BaseAddon) this, 16382, 0, 3, 8, 1085, -1, "horse", 1);// 42
			AddComplexComponent( (BaseAddon) this, 16382, -1, 3, 8, 1085, -1, "horse", 1);// 43
			AddComplexComponent( (BaseAddon) this, 4828, 1, -1, 13, 1096, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 4828, 1, -2, 13, 1096, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 4828, 1, -3, 13, 1096, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 4828, -2, -3, 11, 1096, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 4828, -2, -2, 11, 1096, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 4828, -2, -1, 11, 1096, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 4839, 0, -4, 0, 1096, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 4839, -1, -4, 0, 1096, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 4839, -2, -4, 0, 1096, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 4845, 1, -2, 20, 1096, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 4834, 1, -1, 12, 1096, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 4834, -1, 0, 23, 1096, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 4269, 1, 3, 8, 1096, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 4269, 1, 2, 8, 1096, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 4269, -1, 2, 5, 1096, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 4269, -1, 3, 5, 1096, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3196, 1, -2, 28, 32, -1, "Rose", 1);// 63
			AddComplexComponent( (BaseAddon) this, 3196, 1, -2, 18, 32, -1, "Rose", 1);// 64
			AddComplexComponent( (BaseAddon) this, 3195, 1, -1, 25, 32, -1, "Rose", 1);// 65
			AddComplexComponent( (BaseAddon) this, 3196, 1, -2, 28, 32, -1, "Rose", 1);// 67
			AddComplexComponent( (BaseAddon) this, 3196, 1, -2, 18, 32, -1, "Rose", 1);// 68
			AddComplexComponent( (BaseAddon) this, 3195, 1, -1, 25, 32, -1, "Rose", 1);// 69
			AddComplexComponent( (BaseAddon) this, 3196, 1, -1, 28, 32, -1, "Rose", 1);// 71
			AddComplexComponent( (BaseAddon) this, 3196, 1, -1, 18, 32, -1, "Rose", 1);// 72
			AddComplexComponent( (BaseAddon) this, 3195, 1, 0, 25, 32, -1, "Rose", 1);// 73
			AddComplexComponent( (BaseAddon) this, 3196, 1, -3, 28, 32, -1, "Rose", 1);// 75
			AddComplexComponent( (BaseAddon) this, 3196, 1, -3, 18, 32, -1, "Rose", 1);// 76
			AddComplexComponent( (BaseAddon) this, 3195, 1, -2, 25, 32, -1, "Rose", 1);// 77
			AddComplexComponent( (BaseAddon) this, 3196, 1, -1, 28, 32, -1, "Rose", 1);// 79
			AddComplexComponent( (BaseAddon) this, 3196, 1, -1, 18, 32, -1, "Rose", 1);// 80
			AddComplexComponent( (BaseAddon) this, 3195, 1, 0, 25, 32, -1, "Rose", 1);// 81
			AddComplexComponent( (BaseAddon) this, 3196, 1, 0, 28, 32, -1, "Rose", 1);// 83
			AddComplexComponent( (BaseAddon) this, 3196, 1, 0, 18, 32, -1, "Rose", 1);// 84
			AddComplexComponent( (BaseAddon) this, 3195, 1, 1, 25, 32, -1, "Rose", 1);// 85
			AddComplexComponent( (BaseAddon) this, 3195, -2, 1, 25, 32, -1, "Rose", 1);// 86
			AddComplexComponent( (BaseAddon) this, 3196, -2, 0, 28, 32, -1, "Rose", 1);// 88
			AddComplexComponent( (BaseAddon) this, 3196, -2, 0, 18, 32, -1, "Rose", 1);// 89
			AddComplexComponent( (BaseAddon) this, 3520, -1, 1, 14, 0, -1, "whip", 1);// 90
			AddComplexComponent( (BaseAddon) this, 4269, 1, 4, 8, 1096, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 4269, -1, 4, 5, 1096, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 2594, 0, 4, 9, 0, 29, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 2594, -2, 4, 8, 0, 29, "", 1);// 94

		}

		public HearseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HearseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HearseAddon();
			}
		}

		[Constructable]
		public HearseAddonDeed()
		{
			Name = "Hearse";
		}

		public HearseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}