
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace LargeTermurSoulForge
{
	public class LargeTermurSoulForgeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5360, 0, -2, 0}, {17015, -1, -1, 0}, {17016, 0, -1, 0}// 1	2	3	
			, {17017, 1, -1, 0}, {17018, 2, -1, 0}, {17020, 0, 0, 0}// 4	5	6	
			, {17021, 1, 0, 0}, {17022, 2, 0, 0}, {17024, 0, 1, 0}// 7	8	9	
			, {17025, 1, 1, 0}, {17026, 2, 1, 0}, {17028, 0, 2, 0}// 10	11	12	
			, {17029, 1, 2, 0}, {17030, 2, 2, 0}, {17019, -1, 0, 0}// 13	14	15	
			, {17023, -1, 1, 0}, {17027, -1, 2, 0}// 16	17	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargeTermurSoulForgeAddonDeed();
			}
		}

		[ Constructable ]
		public LargeTermurSoulForgeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LargeTermurSoulForgeAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargeTermurSoulForgeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargeTermurSoulForgeAddon();
			}
		}

		[Constructable]
		public LargeTermurSoulForgeAddonDeed()
		{
			Name = "LargeTermurSoulForge";
		}

		public LargeTermurSoulForgeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}