
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PolarBearWithSunglassesSAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PolarBearWithSunglassesSAddonDeed();
			}
		}

		[ Constructable ]
		public PolarBearWithSunglassesSAddon()
		{



			AddComplexComponent( (BaseAddon) this, 7753, 1, 1, 0, 0, -1, "polarbear", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7754, 0, 1, 0, 0, -1, "polarbear", 1);// 2
			AddComplexComponent( (BaseAddon) this, 7755, -1, 1, 0, 0, -1, "polarbear", 1);// 3
			AddComplexComponent( (BaseAddon) this, 7756, -1, 0, 0, 0, -1, "polarbear", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7757, 0, 0, 0, 0, -1, "polarbear", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7758, 1, 0, 0, 0, -1, "polarbear", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7759, 1, -1, 0, 0, -1, "polarbear", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7760, 0, -1, 0, 0, -1, "polarbear", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7761, -1, -1, 0, 0, -1, "polarbear", 1);// 9
			AddComplexComponent( (BaseAddon) this, 12591, 0, 1, 0, 0, -1, "sunglasses", 1);// 10

		}

		public PolarBearWithSunglassesSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PolarBearWithSunglassesSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PolarBearWithSunglassesSAddon();
			}
		}

		[Constructable]
		public PolarBearWithSunglassesSAddonDeed()
		{
			Name = "PolarBearWithSunglassesS";
		}

		public PolarBearWithSunglassesSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}