
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace TurtleFlowerFountain
{
	public class TurtleFlowerFountainAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2861, 2, -2, 20}, {2861, 1, -2, 20}, {2861, 0, -2, 20}// 1	2	3	
			, {2861, -1, -2, 20}, {2860, -2, -1, 20}, {2860, -2, 0, 20}// 4	5	6	
			, {2860, -2, 1, 20}, {2860, -2, 2, 20}, {22, 1, 2, 20}// 7	8	36	
			, {22, 0, 2, 20}, {22, -1, 2, 20}, {22, 1, -2, 20}// 37	38	39	
			, {22, 1, -2, 20}, {22, 0, -2, 20}, {22, -1, -2, 20}// 40	41	42	
			, {21, -2, -1, 20}, {21, -2, 0, 20}, {21, -2, 1, 20}// 43	44	45	
			, {21, -2, 2, 20}, {21, 2, -1, 20}, {21, 2, 0, 20}// 46	47	48	
			, {21, 2, 1, 20}, {20, 2, 2, 20}, {40087, 1, 2, 23}// 49	50	51	
			, {40089, 0, 1, 23}, {40090, 1, 0, 23}, {40088, 1, 1, 23}// 52	53	54	
			, {1301, -2, -1, 20}, {1301, 1, 1, 20}, {1301, 2, -1, 20}// 59	74	75	
			, {1301, 0, 1, 20}, {1301, 1, -2, 20}, {1301, 0, 2, 20}// 76	77	78	
			, {1301, 1, 0, 20}, {1301, 1, 2, 20}, {1301, -2, 0, 20}// 79	80	81	
			, {1301, 2, 2, 20}, {1301, 2, 1, 20}, {1301, 2, -2, 20}// 86	88	89	
			, {1301, 1, -1, 20}, {1301, -2, -2, 20}, {1301, 2, 0, 20}// 90	91	92	
			, {1301, -1, 2, 20}, {1301, -1, 0, 20}, {1301, -1, 1, 20}// 93	94	95	
			, {1301, -1, -1, 20}, {1301, 0, 0, 20}, {1301, 0, -1, 20}// 96	97	98	
			, {1301, 0, -2, 20}, {1301, -2, 1, 20}, {1301, -2, 2, 20}// 99	100	101	
			, {1301, -1, -2, 20}// 102	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TurtleFlowerFountainAddonDeed();
			}
		}

		[ Constructable ]
		public TurtleFlowerFountainAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6811, 1, -1, 24, 2476, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6811, 0, -1, 24, 2476, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6811, -1, -1, 24, 2476, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6811, -1, 0, 24, 2476, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6811, -1, 1, 24, 2476, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6811, -1, 2, 23, 2476, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6811, 0, 2, 24, 2476, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6811, -1, 2, 24, 2476, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6811, 1, 2, 24, 2476, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6811, 2, -1, 23, 2476, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6811, 2, -1, 24, 2476, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6811, 2, 0, 24, 2476, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6811, 2, 1, 24, 2476, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6811, 2, 2, 24, 2476, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3231, -1, 0, 23, 1368, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3231, 0, -1, 23, 1368, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 3231, -1, -1, 23, 1368, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 3231, -1, 1, 23, 1368, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 3231, -1, 2, 23, 1368, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 3231, -1, 1, 20, 1368, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 3231, 0, 2, 23, 1368, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3231, 2, -1, 23, 1368, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3231, 1, -1, 23, 1368, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3231, 2, 0, 23, 1368, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3231, 2, 1, 23, 1368, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 3231, 2, 2, 23, 1368, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3231, 1, 2, 23, 1368, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1297, -1, 2, 0, 1083, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1297, -1, 1, 0, 1083, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1297, -1, 0, 0, 1083, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1297, 0, -1, 0, 1083, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1297, 0, -2, 0, 1083, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1297, 0, 0, 0, 1083, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1297, 0, 1, 0, 1083, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1297, 0, 2, 0, 1083, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1297, 1, -2, 0, 1083, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1297, 1, -1, 0, 1083, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1297, 1, 0, 0, 1083, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1297, 1, 1, 0, 1083, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1297, 1, 2, 0, 1083, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1297, 2, -2, 0, 1083, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1297, 2, -1, 0, 1083, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1297, 2, 0, 0, 1083, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1297, 2, 1, 0, 1083, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1297, 2, 2, 0, 1083, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1297, -2, -2, 0, 1083, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1297, -2, -1, 0, 1083, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1297, -2, 1, 0, 1083, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1297, -2, 0, 0, 1083, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1297, -2, 2, 0, 1083, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1297, -1, -1, 0, 1083, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1297, -1, -2, 0, 1083, -1, "", 1);// 104

		}

		public TurtleFlowerFountainAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TurtleFlowerFountainAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TurtleFlowerFountainAddon();
			}
		}

		[Constructable]
		public TurtleFlowerFountainAddonDeed()
		{
			Name = "TurtleFlowerFountain";
		}

		public TurtleFlowerFountainAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}