/////////////////////////////////////
//**Generated by Ryans Scripts**//
/////////////////////////////////////
using System;
using Server;

namespace Server.Items
{
	public class NoxRobe : Robe
	{
	 	public override int ArtifactRarity{ get{ return 10; } }

	 	[Constructable]
	 	public NoxRobe()
	 	{
	 	 	Name = "Robe of the Swamp Queen";
	 	 	Hue = 1272;
			Attributes.BonusInt = 15;
			Attributes.BonusMana = 15;
		//	Attributes.BonusStam = 10;
			Attributes.CastRecovery = 2;
			Attributes.CastSpeed = 2;
		//	Attributes.DefendChance = 10;
			Attributes.Luck = 50;
			Attributes.NightSight = 1;
		//	Attributes.ReflectPhysical = 15;
			Attributes.RegenHits = 4;
			Attributes.RegenMana = 4;

	 	}

	 	public NoxRobe(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
