/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmBathroomCounterSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmBathroomCounterSAddonDeed();
			}
		}

		[ Constructable ]
		public SmBathroomCounterSAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 7620 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 7621 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 7622 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4104 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 6420 );
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 4978 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 3625 );
			ac.Name = "Shaving cream";
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 3626 );
			ac.Name = "Hand lotion";
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 3836 );
			ac.Name = "perfume";
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 5154 );
			ac.Name = "Bar of Soap";
			AddComponent( ac, 0, 0, 8 );

		}

		public SmBathroomCounterSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmBathroomCounterSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmBathroomCounterSAddon();
			}
		}

		[Constructable]
		public SmBathroomCounterSAddonDeed()
		{
			Name = "SmBathroomCounterS";
		}

		public SmBathroomCounterSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}