
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WhitePottyEastAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WhitePottyEastAddonDeed();
			}
		}

		[ Constructable ]
		public WhitePottyEastAddon()
		{



			AddComplexComponent( (BaseAddon) this, 19257, 0, 0, 1, 1153, -1, "Tank", 1);// 1
			AddComplexComponent( (BaseAddon) this, 16902, 1, 0, 5, 1050, -1, "Lid", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4240, 1, 0, 7, 1106, -1, "Handle", 1);// 3
			AddComplexComponent( (BaseAddon) this, 19257, 0, 0, 4, 1153, -1, "Tank", 1);// 4
			AddComplexComponent( (BaseAddon) this, 18177, 1, 0, 0, 1153, -1, "Bowl", 1);// 5

		}

		public WhitePottyEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WhitePottyEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WhitePottyEastAddon();
			}
		}

		[Constructable]
		public WhitePottyEastAddonDeed()
		{
			Name = "WhitePottyEast";
		}

		public WhitePottyEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}